//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiicNetModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINKS_DOC : Base
    {
        public string TPDOC { get; set; }
        public int NRFACT { get; set; }
        public string TERCEIRO { get; set; }
        public string ENTIDADE { get; set; }
        public string LINK { get; set; }
        public Nullable<System.DateTime> DATAREG { get; set; }
        public string UTENTE { get; set; }
    }
}
