//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiicNetModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PECAS
    {
        public PECAS()
        {
            this.TEMPLATES = new HashSet<TEMPLATES>();
        }
    
        public string PECA { get; set; }
        public string DESCPECA { get; set; }
        public string DESC_INGLES { get; set; }
        public string DESC_FRANCES { get; set; }
        public string DESC_ESPANHOL { get; set; }
        public string OPERACAO { get; set; }
        public string POSICAO { get; set; }
        public Nullable<double> LIN { get; set; }
        public Nullable<double> COL { get; set; }
        public string GRUPO { get; set; }
    
        public virtual ICollection<TEMPLATES> TEMPLATES { get; set; }
    }
}
