//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiicNetModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_REGRAEMB : Base
    {
        public string CODREGRA { get; set; }
        public string CODEMB { get; set; }
        public int QT { get; set; }
        public string DIMCAIXA { get; set; }
    
        public virtual TABEMB TABEMB { get; set; }
    }
}
