//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiicNetModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABFUNC : Base
    {
        public string CODFUNC { get; set; }
        public string NOME { get; set; }
        public string ABREV { get; set; }
        public string TELEF { get; set; }
        public string CHAVE { get; set; }
        public string GRUPO { get; set; }
        public Nullable<byte> NIVEL { get; set; }
        public Nullable<decimal> PLAFOND { get; set; }
        public Nullable<decimal> ADESC { get; set; }
        public Nullable<decimal> COMISSAO { get; set; }
        public string LOJAS { get; set; }
        public byte[] IMPRESSAODIG { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
