//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiicNetModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABTRAN : Base
    {
        public string CODTRAN { get; set; }
        public string TRANSIT { get; set; }
        public string MORADA1 { get; set; }
        public string MORADA2 { get; set; }
        public string MORADA3 { get; set; }
        public string MORADA4 { get; set; }
        public string TELEF { get; set; }
        public string FAX { get; set; }
        public string CONTACTO { get; set; }
    }
}
