//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.TS_WK_CONSUMOS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdConsumo
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="TS_WK_CONSUMOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TS_WK_CONSUMOS : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new TS_WK_CONSUMOS object.
        /// </summary>
        /// <param name="idConsumo">Initial value of IdConsumo.</param>
        public static TS_WK_CONSUMOS CreateTS_WK_CONSUMOS(string idConsumo)
        {
            TS_WK_CONSUMOS tS_WK_CONSUMOS = new TS_WK_CONSUMOS();
            tS_WK_CONSUMOS.IdConsumo = idConsumo;
            return tS_WK_CONSUMOS;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for IdConsumo in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string IdConsumo
        {
            get
            {
                string value = _IdConsumo;
                OnGetIdConsumo(ref value);
                return value;
            }
            set
            {
                if (_IdConsumo != value)
                {
                  OnIdConsumoChanging(ref value);
                  ReportPropertyChanging("IdConsumo");
                  _IdConsumo = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("IdConsumo");
                  OnIdConsumoChanged();
              }
            }
        }
        private string _IdConsumo;
        partial void OnGetIdConsumo(ref string value);
        partial void OnIdConsumoChanging(ref string value);
        partial void OnIdConsumoChanged();
    
        /// <summary>
        /// There are no comments for MODELO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public string MODELO
        {
            get
            {
                string value = _MODELO;
                OnGetMODELO(ref value);
                return value;
            }
            set
            {
                if (_MODELO != value)
                {
                  OnMODELOChanging(ref value);
                  ReportPropertyChanging("MODELO");
                  _MODELO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("MODELO");
                  OnMODELOChanged();
              }
            }
        }
        private string _MODELO;
        partial void OnGetMODELO(ref string value);
        partial void OnMODELOChanging(ref string value);
        partial void OnMODELOChanged();
    
        /// <summary>
        /// There are no comments for VARIANTE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string VARIANTE
        {
            get
            {
                string value = _VARIANTE;
                OnGetVARIANTE(ref value);
                return value;
            }
            set
            {
                if (_VARIANTE != value)
                {
                  OnVARIANTEChanging(ref value);
                  ReportPropertyChanging("VARIANTE");
                  _VARIANTE = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("VARIANTE");
                  OnVARIANTEChanged();
              }
            }
        }
        private string _VARIANTE;
        partial void OnGetVARIANTE(ref string value);
        partial void OnVARIANTEChanging(ref string value);
        partial void OnVARIANTEChanged();
    
        /// <summary>
        /// There are no comments for FAMILIA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string FAMILIA
        {
            get
            {
                string value = _FAMILIA;
                OnGetFAMILIA(ref value);
                return value;
            }
            set
            {
                if (_FAMILIA != value)
                {
                  OnFAMILIAChanging(ref value);
                  ReportPropertyChanging("FAMILIA");
                  _FAMILIA = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("FAMILIA");
                  OnFAMILIAChanged();
              }
            }
        }
        private string _FAMILIA;
        partial void OnGetFAMILIA(ref string value);
        partial void OnFAMILIAChanging(ref string value);
        partial void OnFAMILIAChanged();
    
        /// <summary>
        /// There are no comments for DESCPECA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string DESCPECA
        {
            get
            {
                string value = _DESCPECA;
                OnGetDESCPECA(ref value);
                return value;
            }
            set
            {
                if (_DESCPECA != value)
                {
                  OnDESCPECAChanging(ref value);
                  ReportPropertyChanging("DESCPECA");
                  _DESCPECA = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DESCPECA");
                  OnDESCPECAChanged();
              }
            }
        }
        private string _DESCPECA;
        partial void OnGetDESCPECA(ref string value);
        partial void OnDESCPECAChanging(ref string value);
        partial void OnDESCPECAChanged();
    
        /// <summary>
        /// There are no comments for COMPONENTE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(12)]
        public string COMPONENTE
        {
            get
            {
                string value = _COMPONENTE;
                OnGetCOMPONENTE(ref value);
                return value;
            }
            set
            {
                if (_COMPONENTE != value)
                {
                  OnCOMPONENTEChanging(ref value);
                  ReportPropertyChanging("COMPONENTE");
                  _COMPONENTE = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("COMPONENTE");
                  OnCOMPONENTEChanged();
              }
            }
        }
        private string _COMPONENTE;
        partial void OnGetCOMPONENTE(ref string value);
        partial void OnCOMPONENTEChanging(ref string value);
        partial void OnCOMPONENTEChanged();
    
        /// <summary>
        /// There are no comments for CODCOR in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string CODCOR
        {
            get
            {
                string value = _CODCOR;
                OnGetCODCOR(ref value);
                return value;
            }
            set
            {
                if (_CODCOR != value)
                {
                  OnCODCORChanging(ref value);
                  ReportPropertyChanging("CODCOR");
                  _CODCOR = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CODCOR");
                  OnCODCORChanged();
              }
            }
        }
        private string _CODCOR;
        partial void OnGetCODCOR(ref string value);
        partial void OnCODCORChanging(ref string value);
        partial void OnCODCORChanged();
    
        /// <summary>
        /// There are no comments for OPERACAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public string OPERACAO
        {
            get
            {
                string value = _OPERACAO;
                OnGetOPERACAO(ref value);
                return value;
            }
            set
            {
                if (_OPERACAO != value)
                {
                  OnOPERACAOChanging(ref value);
                  ReportPropertyChanging("OPERACAO");
                  _OPERACAO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("OPERACAO");
                  OnOPERACAOChanged();
              }
            }
        }
        private string _OPERACAO;
        partial void OnGetOPERACAO(ref string value);
        partial void OnOPERACAOChanging(ref string value);
        partial void OnOPERACAOChanged();
    
        /// <summary>
        /// There are no comments for OBSV in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(60)]
        public string OBSV
        {
            get
            {
                string value = _OBSV;
                OnGetOBSV(ref value);
                return value;
            }
            set
            {
                if (_OBSV != value)
                {
                  OnOBSVChanging(ref value);
                  ReportPropertyChanging("OBSV");
                  _OBSV = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("OBSV");
                  OnOBSVChanged();
              }
            }
        }
        private string _OBSV;
        partial void OnGetOBSV(ref string value);
        partial void OnOBSVChanging(ref string value);
        partial void OnOBSVChanged();
    
        /// <summary>
        /// There are no comments for TAMANHOS in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(120)]
        public string TAMANHOS
        {
            get
            {
                string value = _TAMANHOS;
                OnGetTAMANHOS(ref value);
                return value;
            }
            set
            {
                if (_TAMANHOS != value)
                {
                  OnTAMANHOSChanging(ref value);
                  ReportPropertyChanging("TAMANHOS");
                  _TAMANHOS = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("TAMANHOS");
                  OnTAMANHOSChanged();
              }
            }
        }
        private string _TAMANHOS;
        partial void OnGetTAMANHOS(ref string value);
        partial void OnTAMANHOSChanging(ref string value);
        partial void OnTAMANHOSChanged();
    
        /// <summary>
        /// There are no comments for LISTA_CONSUMOS in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(300)]
        public string LISTA_CONSUMOS
        {
            get
            {
                string value = _LISTA_CONSUMOS;
                OnGetLISTA_CONSUMOS(ref value);
                return value;
            }
            set
            {
                if (_LISTA_CONSUMOS != value)
                {
                  OnLISTA_CONSUMOSChanging(ref value);
                  ReportPropertyChanging("LISTA_CONSUMOS");
                  _LISTA_CONSUMOS = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("LISTA_CONSUMOS");
                  OnLISTA_CONSUMOSChanged();
              }
            }
        }
        private string _LISTA_CONSUMOS;
        partial void OnGetLISTA_CONSUMOS(ref string value);
        partial void OnLISTA_CONSUMOSChanging(ref string value);
        partial void OnLISTA_CONSUMOSChanged();
    
        /// <summary>
        /// There are no comments for LISTA_TAMC in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(120)]
        public string LISTA_TAMC
        {
            get
            {
                string value = _LISTA_TAMC;
                OnGetLISTA_TAMC(ref value);
                return value;
            }
            set
            {
                if (_LISTA_TAMC != value)
                {
                  OnLISTA_TAMCChanging(ref value);
                  ReportPropertyChanging("LISTA_TAMC");
                  _LISTA_TAMC = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("LISTA_TAMC");
                  OnLISTA_TAMCChanged();
              }
            }
        }
        private string _LISTA_TAMC;
        partial void OnGetLISTA_TAMC(ref string value);
        partial void OnLISTA_TAMCChanging(ref string value);
        partial void OnLISTA_TAMCChanged();
    
        /// <summary>
        /// There are no comments for ESTACAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string ESTACAO
        {
            get
            {
                string value = _ESTACAO;
                OnGetESTACAO(ref value);
                return value;
            }
            set
            {
                if (_ESTACAO != value)
                {
                  OnESTACAOChanging(ref value);
                  ReportPropertyChanging("ESTACAO");
                  _ESTACAO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("ESTACAO");
                  OnESTACAOChanged();
              }
            }
        }
        private string _ESTACAO;
        partial void OnGetESTACAO(ref string value);
        partial void OnESTACAOChanging(ref string value);
        partial void OnESTACAOChanged();
    
        /// <summary>
        /// There are no comments for REF in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string REF
        {
            get
            {
                string value = _REF;
                OnGetREF(ref value);
                return value;
            }
            set
            {
                if (_REF != value)
                {
                  OnREFChanging(ref value);
                  ReportPropertyChanging("REF");
                  _REF = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("REF");
                  OnREFChanged();
              }
            }
        }
        private string _REF;
        partial void OnGetREF(ref string value);
        partial void OnREFChanging(ref string value);
        partial void OnREFChanged();
    
        /// <summary>
        /// There are no comments for PECA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string PECA
        {
            get
            {
                string value = _PECA;
                OnGetPECA(ref value);
                return value;
            }
            set
            {
                if (_PECA != value)
                {
                  OnPECAChanging(ref value);
                  ReportPropertyChanging("PECA");
                  _PECA = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("PECA");
                  OnPECAChanged();
              }
            }
        }
        private string _PECA;
        partial void OnGetPECA(ref string value);
        partial void OnPECAChanging(ref string value);
        partial void OnPECAChanged();
    
        /// <summary>
        /// There are no comments for TAM in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string TAM
        {
            get
            {
                string value = _TAM;
                OnGetTAM(ref value);
                return value;
            }
            set
            {
                if (_TAM != value)
                {
                  OnTAMChanging(ref value);
                  ReportPropertyChanging("TAM");
                  _TAM = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("TAM");
                  OnTAMChanged();
              }
            }
        }
        private string _TAM;
        partial void OnGetTAM(ref string value);
        partial void OnTAMChanging(ref string value);
        partial void OnTAMChanged();
    
        /// <summary>
        /// There are no comments for CONSUMO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> CONSUMO
        {
            get
            {
                global::System.Nullable<decimal> value = _CONSUMO;
                OnGetCONSUMO(ref value);
                return value;
            }
            set
            {
                if (_CONSUMO != value)
                {
                  OnCONSUMOChanging(ref value);
                  ReportPropertyChanging("CONSUMO");
                  _CONSUMO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("CONSUMO");
                  OnCONSUMOChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _CONSUMO;
        partial void OnGetCONSUMO(ref global::System.Nullable<decimal> value);
        partial void OnCONSUMOChanging(ref global::System.Nullable<decimal> value);
        partial void OnCONSUMOChanged();
    
        /// <summary>
        /// There are no comments for UNMED in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(15)]
        public string UNMED
        {
            get
            {
                string value = _UNMED;
                OnGetUNMED(ref value);
                return value;
            }
            set
            {
                if (_UNMED != value)
                {
                  OnUNMEDChanging(ref value);
                  ReportPropertyChanging("UNMED");
                  _UNMED = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("UNMED");
                  OnUNMEDChanged();
              }
            }
        }
        private string _UNMED;
        partial void OnGetUNMED(ref string value);
        partial void OnUNMEDChanging(ref string value);
        partial void OnUNMEDChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            TS_WK_CONSUMOS obj = new TS_WK_CONSUMOS();
            obj.IdConsumo = IdConsumo;
            obj.MODELO = MODELO;
            obj.VARIANTE = VARIANTE;
            obj.FAMILIA = FAMILIA;
            obj.DESCPECA = DESCPECA;
            obj.COMPONENTE = COMPONENTE;
            obj.CODCOR = CODCOR;
            obj.OPERACAO = OPERACAO;
            obj.OBSV = OBSV;
            obj.TAMANHOS = TAMANHOS;
            obj.LISTA_CONSUMOS = LISTA_CONSUMOS;
            obj.LISTA_TAMC = LISTA_TAMC;
            obj.ESTACAO = ESTACAO;
            obj.REF = REF;
            obj.PECA = PECA;
            obj.TAM = TAM;
            obj.CONSUMO = CONSUMO;
            obj.UNMED = UNMED;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          TS_WK_CONSUMOS toCompare = obj as TS_WK_CONSUMOS;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IdConsumo, toCompare.IdConsumo))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IdConsumo.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
