//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.TABDIA in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODDIARIO
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="TABDIA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TABDIA : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new TABDIA object.
        /// </summary>
        /// <param name="cODDIARIO">Initial value of CODDIARIO.</param>
        public static TABDIA CreateTABDIA(string cODDIARIO)
        {
            TABDIA tABDIA = new TABDIA();
            tABDIA.CODDIARIO = cODDIARIO;
            return tABDIA;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for CODDIARIO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string CODDIARIO
        {
            get
            {
                string value = _CODDIARIO;
                OnGetCODDIARIO(ref value);
                return value;
            }
            set
            {
                if (_CODDIARIO != value)
                {
                  OnCODDIARIOChanging(ref value);
                  ReportPropertyChanging("CODDIARIO");
                  _CODDIARIO = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("CODDIARIO");
                  OnCODDIARIOChanged();
              }
            }
        }
        private string _CODDIARIO;
        partial void OnGetCODDIARIO(ref string value);
        partial void OnCODDIARIOChanging(ref string value);
        partial void OnCODDIARIOChanged();
    
        /// <summary>
        /// There are no comments for DESCRICAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(35)]
        public string DESCRICAO
        {
            get
            {
                string value = _DESCRICAO;
                OnGetDESCRICAO(ref value);
                return value;
            }
            set
            {
                if (_DESCRICAO != value)
                {
                  OnDESCRICAOChanging(ref value);
                  ReportPropertyChanging("DESCRICAO");
                  _DESCRICAO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DESCRICAO");
                  OnDESCRICAOChanged();
              }
            }
        }
        private string _DESCRICAO;
        partial void OnGetDESCRICAO(ref string value);
        partial void OnDESCRICAOChanging(ref string value);
        partial void OnDESCRICAOChanged();
    
        /// <summary>
        /// There are no comments for ULTDOC in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<double> ULTDOC
        {
            get
            {
                global::System.Nullable<double> value = _ULTDOC;
                OnGetULTDOC(ref value);
                return value;
            }
            set
            {
                if (_ULTDOC != value)
                {
                  OnULTDOCChanging(ref value);
                  ReportPropertyChanging("ULTDOC");
                  _ULTDOC = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("ULTDOC");
                  OnULTDOCChanged();
              }
            }
        }
        private global::System.Nullable<double> _ULTDOC;
        partial void OnGetULTDOC(ref global::System.Nullable<double> value);
        partial void OnULTDOCChanging(ref global::System.Nullable<double> value);
        partial void OnULTDOCChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            TABDIA obj = new TABDIA();
            obj.CODDIARIO = CODDIARIO;
            obj.DESCRICAO = DESCRICAO;
            obj.ULTDOC = ULTDOC;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          TABDIA toCompare = obj as TABDIA;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.CODDIARIO, toCompare.CODDIARIO))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + CODDIARIO.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
