//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.ENCO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NRENCO
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="ENCO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ENCO : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new ENCO object.
        /// </summary>
        /// <param name="nRENCO">Initial value of NRENCO.</param>
        /// <param name="gRIFO_CARTAZ">Initial value of GRIFO_CARTAZ.</param>
        /// <param name="gRIFO_CODCOR">Initial value of GRIFO_CODCOR.</param>
        /// <param name="sTATUSNR">Initial value of STATUSNR.</param>
        public static ENCO CreateENCO(string nRENCO, string gRIFO_CARTAZ, string gRIFO_CODCOR, bool sTATUSNR)
        {
            ENCO eNCO = new ENCO();
            eNCO.NRENCO = nRENCO;
            eNCO.GRIFO_CARTAZ = gRIFO_CARTAZ;
            eNCO.GRIFO_CODCOR = gRIFO_CODCOR;
            eNCO.STATUSNR = sTATUSNR;
            return eNCO;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for NRENCO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(6)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string NRENCO
        {
            get
            {
                string value = _NRENCO;
                OnGetNRENCO(ref value);
                return value;
            }
            set
            {
                if (_NRENCO != value)
                {
                  OnNRENCOChanging(ref value);
                  ReportPropertyChanging("NRENCO");
                  _NRENCO = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("NRENCO");
                  OnNRENCOChanged();
              }
            }
        }
        private string _NRENCO;
        partial void OnGetNRENCO(ref string value);
        partial void OnNRENCOChanging(ref string value);
        partial void OnNRENCOChanged();
    
        /// <summary>
        /// There are no comments for ENCOCLI in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string ENCOCLI
        {
            get
            {
                string value = _ENCOCLI;
                OnGetENCOCLI(ref value);
                return value;
            }
            set
            {
                if (_ENCOCLI != value)
                {
                  OnENCOCLIChanging(ref value);
                  ReportPropertyChanging("ENCOCLI");
                  _ENCOCLI = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("ENCOCLI");
                  OnENCOCLIChanged();
              }
            }
        }
        private string _ENCOCLI;
        partial void OnGetENCOCLI(ref string value);
        partial void OnENCOCLIChanging(ref string value);
        partial void OnENCOCLIChanged();
    
        /// <summary>
        /// There are no comments for CLIENTE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(5)]
        public string CLIENTE
        {
            get
            {
                string value = _CLIENTE;
                OnGetCLIENTE(ref value);
                return value;
            }
            set
            {
                if (_CLIENTE != value)
                {
                  OnCLIENTEChanging(ref value);
                  ReportPropertyChanging("CLIENTE");
                  _CLIENTE = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CLIENTE");
                  OnCLIENTEChanged();
              }
            }
        }
        private string _CLIENTE;
        partial void OnGetCLIENTE(ref string value);
        partial void OnCLIENTEChanging(ref string value);
        partial void OnCLIENTEChanged();
    
        /// <summary>
        /// There are no comments for NRMORADA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> NRMORADA
        {
            get
            {
                global::System.Nullable<int> value = _NRMORADA;
                OnGetNRMORADA(ref value);
                return value;
            }
            set
            {
                if (_NRMORADA != value)
                {
                  OnNRMORADAChanging(ref value);
                  ReportPropertyChanging("NRMORADA");
                  _NRMORADA = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("NRMORADA");
                  OnNRMORADAChanged();
              }
            }
        }
        private global::System.Nullable<int> _NRMORADA = 0;
        partial void OnGetNRMORADA(ref global::System.Nullable<int> value);
        partial void OnNRMORADAChanging(ref global::System.Nullable<int> value);
        partial void OnNRMORADAChanged();
    
        /// <summary>
        /// There are no comments for ESTACAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string ESTACAO
        {
            get
            {
                string value = _ESTACAO;
                OnGetESTACAO(ref value);
                return value;
            }
            set
            {
                if (_ESTACAO != value)
                {
                  OnESTACAOChanging(ref value);
                  ReportPropertyChanging("ESTACAO");
                  _ESTACAO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("ESTACAO");
                  OnESTACAOChanged();
              }
            }
        }
        private string _ESTACAO;
        partial void OnGetESTACAO(ref string value);
        partial void OnESTACAOChanging(ref string value);
        partial void OnESTACAOChanged();
    
        /// <summary>
        /// There are no comments for MARCA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(15)]
        public string MARCA
        {
            get
            {
                string value = _MARCA;
                OnGetMARCA(ref value);
                return value;
            }
            set
            {
                if (_MARCA != value)
                {
                  OnMARCAChanging(ref value);
                  ReportPropertyChanging("MARCA");
                  _MARCA = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("MARCA");
                  OnMARCAChanged();
              }
            }
        }
        private string _MARCA;
        partial void OnGetMARCA(ref string value);
        partial void OnMARCAChanging(ref string value);
        partial void OnMARCAChanged();
    
        /// <summary>
        /// There are no comments for GRIFO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(12)]
        public string GRIFO
        {
            get
            {
                string value = _GRIFO;
                OnGetGRIFO(ref value);
                return value;
            }
            set
            {
                if (_GRIFO != value)
                {
                  OnGRIFOChanging(ref value);
                  ReportPropertyChanging("GRIFO");
                  _GRIFO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("GRIFO");
                  OnGRIFOChanged();
              }
            }
        }
        private string _GRIFO;
        partial void OnGetGRIFO(ref string value);
        partial void OnGRIFOChanging(ref string value);
        partial void OnGRIFOChanged();
    
        /// <summary>
        /// There are no comments for GRIFO_CARTAZ in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(5)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string GRIFO_CARTAZ
        {
            get
            {
                string value = _GRIFO_CARTAZ;
                OnGetGRIFO_CARTAZ(ref value);
                return value;
            }
            set
            {
                if (_GRIFO_CARTAZ != value)
                {
                  OnGRIFO_CARTAZChanging(ref value);
                  ReportPropertyChanging("GRIFO_CARTAZ");
                  _GRIFO_CARTAZ = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("GRIFO_CARTAZ");
                  OnGRIFO_CARTAZChanged();
              }
            }
        }
        private string _GRIFO_CARTAZ = @"space((5))";
        partial void OnGetGRIFO_CARTAZ(ref string value);
        partial void OnGRIFO_CARTAZChanging(ref string value);
        partial void OnGRIFO_CARTAZChanged();
    
        /// <summary>
        /// There are no comments for GRIFO_CODCOR in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string GRIFO_CODCOR
        {
            get
            {
                string value = _GRIFO_CODCOR;
                OnGetGRIFO_CODCOR(ref value);
                return value;
            }
            set
            {
                if (_GRIFO_CODCOR != value)
                {
                  OnGRIFO_CODCORChanging(ref value);
                  ReportPropertyChanging("GRIFO_CODCOR");
                  _GRIFO_CODCOR = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("GRIFO_CODCOR");
                  OnGRIFO_CODCORChanged();
              }
            }
        }
        private string _GRIFO_CODCOR = @"space((3))";
        partial void OnGetGRIFO_CODCOR(ref string value);
        partial void OnGRIFO_CODCORChanging(ref string value);
        partial void OnGRIFO_CODCORChanged();
    
        /// <summary>
        /// There are no comments for DATAENCO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> DATAENCO
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _DATAENCO;
                OnGetDATAENCO(ref value);
                return value;
            }
            set
            {
                if (_DATAENCO != value)
                {
                  OnDATAENCOChanging(ref value);
                  ReportPropertyChanging("DATAENCO");
                  _DATAENCO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DATAENCO");
                  OnDATAENCOChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _DATAENCO;
        partial void OnGetDATAENCO(ref global::System.Nullable<System.DateTime> value);
        partial void OnDATAENCOChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnDATAENCOChanged();
    
        /// <summary>
        /// There are no comments for PROCESSO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string PROCESSO
        {
            get
            {
                string value = _PROCESSO;
                OnGetPROCESSO(ref value);
                return value;
            }
            set
            {
                if (_PROCESSO != value)
                {
                  OnPROCESSOChanging(ref value);
                  ReportPropertyChanging("PROCESSO");
                  _PROCESSO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("PROCESSO");
                  OnPROCESSOChanged();
              }
            }
        }
        private string _PROCESSO;
        partial void OnGetPROCESSO(ref string value);
        partial void OnPROCESSOChanging(ref string value);
        partial void OnPROCESSOChanged();
    
        /// <summary>
        /// There are no comments for PRAZO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> PRAZO
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _PRAZO;
                OnGetPRAZO(ref value);
                return value;
            }
            set
            {
                if (_PRAZO != value)
                {
                  OnPRAZOChanging(ref value);
                  ReportPropertyChanging("PRAZO");
                  _PRAZO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PRAZO");
                  OnPRAZOChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _PRAZO;
        partial void OnGetPRAZO(ref global::System.Nullable<System.DateTime> value);
        partial void OnPRAZOChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnPRAZOChanged();
    
        /// <summary>
        /// There are no comments for MOEDA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string MOEDA
        {
            get
            {
                string value = _MOEDA;
                OnGetMOEDA(ref value);
                return value;
            }
            set
            {
                if (_MOEDA != value)
                {
                  OnMOEDAChanging(ref value);
                  ReportPropertyChanging("MOEDA");
                  _MOEDA = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("MOEDA");
                  OnMOEDAChanged();
              }
            }
        }
        private string _MOEDA;
        partial void OnGetMOEDA(ref string value);
        partial void OnMOEDAChanging(ref string value);
        partial void OnMOEDAChanged();
    
        /// <summary>
        /// There are no comments for CAMBIO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> CAMBIO
        {
            get
            {
                global::System.Nullable<decimal> value = _CAMBIO;
                OnGetCAMBIO(ref value);
                return value;
            }
            set
            {
                if (_CAMBIO != value)
                {
                  OnCAMBIOChanging(ref value);
                  ReportPropertyChanging("CAMBIO");
                  _CAMBIO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("CAMBIO");
                  OnCAMBIOChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _CAMBIO = 1m;
        partial void OnGetCAMBIO(ref global::System.Nullable<decimal> value);
        partial void OnCAMBIOChanging(ref global::System.Nullable<decimal> value);
        partial void OnCAMBIOChanged();
    
        /// <summary>
        /// There are no comments for CNDPAG in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string CNDPAG
        {
            get
            {
                string value = _CNDPAG;
                OnGetCNDPAG(ref value);
                return value;
            }
            set
            {
                if (_CNDPAG != value)
                {
                  OnCNDPAGChanging(ref value);
                  ReportPropertyChanging("CNDPAG");
                  _CNDPAG = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CNDPAG");
                  OnCNDPAGChanged();
              }
            }
        }
        private string _CNDPAG;
        partial void OnGetCNDPAG(ref string value);
        partial void OnCNDPAGChanging(ref string value);
        partial void OnCNDPAGChanged();
    
        /// <summary>
        /// There are no comments for ID_CONTA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public string ID_CONTA
        {
            get
            {
                string value = _ID_CONTA;
                OnGetID_CONTA(ref value);
                return value;
            }
            set
            {
                if (_ID_CONTA != value)
                {
                  OnID_CONTAChanging(ref value);
                  ReportPropertyChanging("ID_CONTA");
                  _ID_CONTA = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("ID_CONTA");
                  OnID_CONTAChanged();
              }
            }
        }
        private string _ID_CONTA;
        partial void OnGetID_CONTA(ref string value);
        partial void OnID_CONTAChanging(ref string value);
        partial void OnID_CONTAChanged();
    
        /// <summary>
        /// There are no comments for AGENTE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string AGENTE
        {
            get
            {
                string value = _AGENTE;
                OnGetAGENTE(ref value);
                return value;
            }
            set
            {
                if (_AGENTE != value)
                {
                  OnAGENTEChanging(ref value);
                  ReportPropertyChanging("AGENTE");
                  _AGENTE = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("AGENTE");
                  OnAGENTEChanged();
              }
            }
        }
        private string _AGENTE;
        partial void OnGetAGENTE(ref string value);
        partial void OnAGENTEChanging(ref string value);
        partial void OnAGENTEChanged();
    
        /// <summary>
        /// There are no comments for AGENTE1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string AGENTE1
        {
            get
            {
                string value = _AGENTE1;
                OnGetAGENTE1(ref value);
                return value;
            }
            set
            {
                if (_AGENTE1 != value)
                {
                  OnAGENTE1Changing(ref value);
                  ReportPropertyChanging("AGENTE1");
                  _AGENTE1 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("AGENTE1");
                  OnAGENTE1Changed();
              }
            }
        }
        private string _AGENTE1;
        partial void OnGetAGENTE1(ref string value);
        partial void OnAGENTE1Changing(ref string value);
        partial void OnAGENTE1Changed();
    
        /// <summary>
        /// There are no comments for AGENTE2 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string AGENTE2
        {
            get
            {
                string value = _AGENTE2;
                OnGetAGENTE2(ref value);
                return value;
            }
            set
            {
                if (_AGENTE2 != value)
                {
                  OnAGENTE2Changing(ref value);
                  ReportPropertyChanging("AGENTE2");
                  _AGENTE2 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("AGENTE2");
                  OnAGENTE2Changed();
              }
            }
        }
        private string _AGENTE2;
        partial void OnGetAGENTE2(ref string value);
        partial void OnAGENTE2Changing(ref string value);
        partial void OnAGENTE2Changed();
    
        /// <summary>
        /// There are no comments for AGENTE3 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string AGENTE3
        {
            get
            {
                string value = _AGENTE3;
                OnGetAGENTE3(ref value);
                return value;
            }
            set
            {
                if (_AGENTE3 != value)
                {
                  OnAGENTE3Changing(ref value);
                  ReportPropertyChanging("AGENTE3");
                  _AGENTE3 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("AGENTE3");
                  OnAGENTE3Changed();
              }
            }
        }
        private string _AGENTE3;
        partial void OnGetAGENTE3(ref string value);
        partial void OnAGENTE3Changing(ref string value);
        partial void OnAGENTE3Changed();
    
        /// <summary>
        /// There are no comments for COMISSAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> COMISSAO
        {
            get
            {
                global::System.Nullable<decimal> value = _COMISSAO;
                OnGetCOMISSAO(ref value);
                return value;
            }
            set
            {
                if (_COMISSAO != value)
                {
                  OnCOMISSAOChanging(ref value);
                  ReportPropertyChanging("COMISSAO");
                  _COMISSAO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("COMISSAO");
                  OnCOMISSAOChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _COMISSAO = 0m;
        partial void OnGetCOMISSAO(ref global::System.Nullable<decimal> value);
        partial void OnCOMISSAOChanging(ref global::System.Nullable<decimal> value);
        partial void OnCOMISSAOChanged();
    
        /// <summary>
        /// There are no comments for COMISSAO1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> COMISSAO1
        {
            get
            {
                global::System.Nullable<decimal> value = _COMISSAO1;
                OnGetCOMISSAO1(ref value);
                return value;
            }
            set
            {
                if (_COMISSAO1 != value)
                {
                  OnCOMISSAO1Changing(ref value);
                  ReportPropertyChanging("COMISSAO1");
                  _COMISSAO1 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("COMISSAO1");
                  OnCOMISSAO1Changed();
              }
            }
        }
        private global::System.Nullable<decimal> _COMISSAO1 = 0m;
        partial void OnGetCOMISSAO1(ref global::System.Nullable<decimal> value);
        partial void OnCOMISSAO1Changing(ref global::System.Nullable<decimal> value);
        partial void OnCOMISSAO1Changed();
    
        /// <summary>
        /// There are no comments for COMISSAO2 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> COMISSAO2
        {
            get
            {
                global::System.Nullable<decimal> value = _COMISSAO2;
                OnGetCOMISSAO2(ref value);
                return value;
            }
            set
            {
                if (_COMISSAO2 != value)
                {
                  OnCOMISSAO2Changing(ref value);
                  ReportPropertyChanging("COMISSAO2");
                  _COMISSAO2 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("COMISSAO2");
                  OnCOMISSAO2Changed();
              }
            }
        }
        private global::System.Nullable<decimal> _COMISSAO2 = 0m;
        partial void OnGetCOMISSAO2(ref global::System.Nullable<decimal> value);
        partial void OnCOMISSAO2Changing(ref global::System.Nullable<decimal> value);
        partial void OnCOMISSAO2Changed();
    
        /// <summary>
        /// There are no comments for COMISSAO3 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> COMISSAO3
        {
            get
            {
                global::System.Nullable<decimal> value = _COMISSAO3;
                OnGetCOMISSAO3(ref value);
                return value;
            }
            set
            {
                if (_COMISSAO3 != value)
                {
                  OnCOMISSAO3Changing(ref value);
                  ReportPropertyChanging("COMISSAO3");
                  _COMISSAO3 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("COMISSAO3");
                  OnCOMISSAO3Changed();
              }
            }
        }
        private global::System.Nullable<decimal> _COMISSAO3 = 0m;
        partial void OnGetCOMISSAO3(ref global::System.Nullable<decimal> value);
        partial void OnCOMISSAO3Changing(ref global::System.Nullable<decimal> value);
        partial void OnCOMISSAO3Changed();
    
        /// <summary>
        /// There are no comments for CATALOGO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(15)]
        public string CATALOGO
        {
            get
            {
                string value = _CATALOGO;
                OnGetCATALOGO(ref value);
                return value;
            }
            set
            {
                if (_CATALOGO != value)
                {
                  OnCATALOGOChanging(ref value);
                  ReportPropertyChanging("CATALOGO");
                  _CATALOGO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CATALOGO");
                  OnCATALOGOChanged();
              }
            }
        }
        private string _CATALOGO;
        partial void OnGetCATALOGO(ref string value);
        partial void OnCATALOGOChanging(ref string value);
        partial void OnCATALOGOChanged();
    
        /// <summary>
        /// There are no comments for TARIFA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string TARIFA
        {
            get
            {
                string value = _TARIFA;
                OnGetTARIFA(ref value);
                return value;
            }
            set
            {
                if (_TARIFA != value)
                {
                  OnTARIFAChanging(ref value);
                  ReportPropertyChanging("TARIFA");
                  _TARIFA = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("TARIFA");
                  OnTARIFAChanged();
              }
            }
        }
        private string _TARIFA;
        partial void OnGetTARIFA(ref string value);
        partial void OnTARIFAChanging(ref string value);
        partial void OnTARIFAChanged();
    
        /// <summary>
        /// There are no comments for COEF in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> COEF
        {
            get
            {
                global::System.Nullable<decimal> value = _COEF;
                OnGetCOEF(ref value);
                return value;
            }
            set
            {
                if (_COEF != value)
                {
                  OnCOEFChanging(ref value);
                  ReportPropertyChanging("COEF");
                  _COEF = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("COEF");
                  OnCOEFChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _COEF;
        partial void OnGetCOEF(ref global::System.Nullable<decimal> value);
        partial void OnCOEFChanging(ref global::System.Nullable<decimal> value);
        partial void OnCOEFChanged();
    
        /// <summary>
        /// There are no comments for NRREGCAT in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string NRREGCAT
        {
            get
            {
                string value = _NRREGCAT;
                OnGetNRREGCAT(ref value);
                return value;
            }
            set
            {
                if (_NRREGCAT != value)
                {
                  OnNRREGCATChanging(ref value);
                  ReportPropertyChanging("NRREGCAT");
                  _NRREGCAT = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("NRREGCAT");
                  OnNRREGCATChanged();
              }
            }
        }
        private string _NRREGCAT;
        partial void OnGetNRREGCAT(ref string value);
        partial void OnNRREGCATChanging(ref string value);
        partial void OnNRREGCATChanged();
    
        /// <summary>
        /// There are no comments for CODMT in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string CODMT
        {
            get
            {
                string value = _CODMT;
                OnGetCODMT(ref value);
                return value;
            }
            set
            {
                if (_CODMT != value)
                {
                  OnCODMTChanging(ref value);
                  ReportPropertyChanging("CODMT");
                  _CODMT = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CODMT");
                  OnCODMTChanged();
              }
            }
        }
        private string _CODMT;
        partial void OnGetCODMT(ref string value);
        partial void OnCODMTChanging(ref string value);
        partial void OnCODMTChanged();
    
        /// <summary>
        /// There are no comments for CODTRAN in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string CODTRAN
        {
            get
            {
                string value = _CODTRAN;
                OnGetCODTRAN(ref value);
                return value;
            }
            set
            {
                if (_CODTRAN != value)
                {
                  OnCODTRANChanging(ref value);
                  ReportPropertyChanging("CODTRAN");
                  _CODTRAN = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CODTRAN");
                  OnCODTRANChanged();
              }
            }
        }
        private string _CODTRAN;
        partial void OnGetCODTRAN(ref string value);
        partial void OnCODTRANChanging(ref string value);
        partial void OnCODTRANChanged();
    
        /// <summary>
        /// There are no comments for TRANSIT in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string TRANSIT
        {
            get
            {
                string value = _TRANSIT;
                OnGetTRANSIT(ref value);
                return value;
            }
            set
            {
                if (_TRANSIT != value)
                {
                  OnTRANSITChanging(ref value);
                  ReportPropertyChanging("TRANSIT");
                  _TRANSIT = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("TRANSIT");
                  OnTRANSITChanged();
              }
            }
        }
        private string _TRANSIT;
        partial void OnGetTRANSIT(ref string value);
        partial void OnTRANSITChanging(ref string value);
        partial void OnTRANSITChanged();
    
        /// <summary>
        /// There are no comments for CNDENT in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string CNDENT
        {
            get
            {
                string value = _CNDENT;
                OnGetCNDENT(ref value);
                return value;
            }
            set
            {
                if (_CNDENT != value)
                {
                  OnCNDENTChanging(ref value);
                  ReportPropertyChanging("CNDENT");
                  _CNDENT = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CNDENT");
                  OnCNDENTChanged();
              }
            }
        }
        private string _CNDENT;
        partial void OnGetCNDENT(ref string value);
        partial void OnCNDENTChanging(ref string value);
        partial void OnCNDENTChanged();
    
        /// <summary>
        /// There are no comments for DESC1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> DESC1
        {
            get
            {
                global::System.Nullable<decimal> value = _DESC1;
                OnGetDESC1(ref value);
                return value;
            }
            set
            {
                if (_DESC1 != value)
                {
                  OnDESC1Changing(ref value);
                  ReportPropertyChanging("DESC1");
                  _DESC1 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DESC1");
                  OnDESC1Changed();
              }
            }
        }
        private global::System.Nullable<decimal> _DESC1;
        partial void OnGetDESC1(ref global::System.Nullable<decimal> value);
        partial void OnDESC1Changing(ref global::System.Nullable<decimal> value);
        partial void OnDESC1Changed();
    
        /// <summary>
        /// There are no comments for DESC2 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> DESC2
        {
            get
            {
                global::System.Nullable<decimal> value = _DESC2;
                OnGetDESC2(ref value);
                return value;
            }
            set
            {
                if (_DESC2 != value)
                {
                  OnDESC2Changing(ref value);
                  ReportPropertyChanging("DESC2");
                  _DESC2 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DESC2");
                  OnDESC2Changed();
              }
            }
        }
        private global::System.Nullable<decimal> _DESC2;
        partial void OnGetDESC2(ref global::System.Nullable<decimal> value);
        partial void OnDESC2Changing(ref global::System.Nullable<decimal> value);
        partial void OnDESC2Changed();
    
        /// <summary>
        /// There are no comments for DESC3 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> DESC3
        {
            get
            {
                global::System.Nullable<decimal> value = _DESC3;
                OnGetDESC3(ref value);
                return value;
            }
            set
            {
                if (_DESC3 != value)
                {
                  OnDESC3Changing(ref value);
                  ReportPropertyChanging("DESC3");
                  _DESC3 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DESC3");
                  OnDESC3Changed();
              }
            }
        }
        private global::System.Nullable<decimal> _DESC3;
        partial void OnGetDESC3(ref global::System.Nullable<decimal> value);
        partial void OnDESC3Changing(ref global::System.Nullable<decimal> value);
        partial void OnDESC3Changed();
    
        /// <summary>
        /// There are no comments for TOTALENC in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> TOTALENC
        {
            get
            {
                global::System.Nullable<int> value = _TOTALENC;
                OnGetTOTALENC(ref value);
                return value;
            }
            set
            {
                if (_TOTALENC != value)
                {
                  OnTOTALENCChanging(ref value);
                  ReportPropertyChanging("TOTALENC");
                  _TOTALENC = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("TOTALENC");
                  OnTOTALENCChanged();
              }
            }
        }
        private global::System.Nullable<int> _TOTALENC;
        partial void OnGetTOTALENC(ref global::System.Nullable<int> value);
        partial void OnTOTALENCChanging(ref global::System.Nullable<int> value);
        partial void OnTOTALENCChanged();
    
        /// <summary>
        /// There are no comments for TOTALEXP in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> TOTALEXP
        {
            get
            {
                global::System.Nullable<int> value = _TOTALEXP;
                OnGetTOTALEXP(ref value);
                return value;
            }
            set
            {
                if (_TOTALEXP != value)
                {
                  OnTOTALEXPChanging(ref value);
                  ReportPropertyChanging("TOTALEXP");
                  _TOTALEXP = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("TOTALEXP");
                  OnTOTALEXPChanged();
              }
            }
        }
        private global::System.Nullable<int> _TOTALEXP;
        partial void OnGetTOTALEXP(ref global::System.Nullable<int> value);
        partial void OnTOTALEXPChanging(ref global::System.Nullable<int> value);
        partial void OnTOTALEXPChanged();
    
        /// <summary>
        /// There are no comments for TOTSALDO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> TOTSALDO
        {
            get
            {
                global::System.Nullable<int> value = _TOTSALDO;
                OnGetTOTSALDO(ref value);
                return value;
            }
            set
            {
                if (_TOTSALDO != value)
                {
                  OnTOTSALDOChanging(ref value);
                  ReportPropertyChanging("TOTSALDO");
                  _TOTSALDO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("TOTSALDO");
                  OnTOTSALDOChanged();
              }
            }
        }
        private global::System.Nullable<int> _TOTSALDO;
        partial void OnGetTOTSALDO(ref global::System.Nullable<int> value);
        partial void OnTOTSALDOChanging(ref global::System.Nullable<int> value);
        partial void OnTOTSALDOChanged();
    
        /// <summary>
        /// There are no comments for VALORENC in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> VALORENC
        {
            get
            {
                global::System.Nullable<decimal> value = _VALORENC;
                OnGetVALORENC(ref value);
                return value;
            }
            set
            {
                if (_VALORENC != value)
                {
                  OnVALORENCChanging(ref value);
                  ReportPropertyChanging("VALORENC");
                  _VALORENC = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("VALORENC");
                  OnVALORENCChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _VALORENC;
        partial void OnGetVALORENC(ref global::System.Nullable<decimal> value);
        partial void OnVALORENCChanging(ref global::System.Nullable<decimal> value);
        partial void OnVALORENCChanged();
    
        /// <summary>
        /// There are no comments for TDESCLNENC in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> TDESCLNENC
        {
            get
            {
                global::System.Nullable<decimal> value = _TDESCLNENC;
                OnGetTDESCLNENC(ref value);
                return value;
            }
            set
            {
                if (_TDESCLNENC != value)
                {
                  OnTDESCLNENCChanging(ref value);
                  ReportPropertyChanging("TDESCLNENC");
                  _TDESCLNENC = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("TDESCLNENC");
                  OnTDESCLNENCChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _TDESCLNENC;
        partial void OnGetTDESCLNENC(ref global::System.Nullable<decimal> value);
        partial void OnTDESCLNENCChanging(ref global::System.Nullable<decimal> value);
        partial void OnTDESCLNENCChanged();
    
        /// <summary>
        /// There are no comments for DESCONTOS in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<double> DESCONTOS
        {
            get
            {
                global::System.Nullable<double> value = _DESCONTOS;
                OnGetDESCONTOS(ref value);
                return value;
            }
            set
            {
                if (_DESCONTOS != value)
                {
                  OnDESCONTOSChanging(ref value);
                  ReportPropertyChanging("DESCONTOS");
                  _DESCONTOS = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DESCONTOS");
                  OnDESCONTOSChanged();
              }
            }
        }
        private global::System.Nullable<double> _DESCONTOS;
        partial void OnGetDESCONTOS(ref global::System.Nullable<double> value);
        partial void OnDESCONTOSChanging(ref global::System.Nullable<double> value);
        partial void OnDESCONTOSChanged();
    
        /// <summary>
        /// There are no comments for PORTES in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> PORTES
        {
            get
            {
                global::System.Nullable<decimal> value = _PORTES;
                OnGetPORTES(ref value);
                return value;
            }
            set
            {
                if (_PORTES != value)
                {
                  OnPORTESChanging(ref value);
                  ReportPropertyChanging("PORTES");
                  _PORTES = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PORTES");
                  OnPORTESChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _PORTES = 0m;
        partial void OnGetPORTES(ref global::System.Nullable<decimal> value);
        partial void OnPORTESChanging(ref global::System.Nullable<decimal> value);
        partial void OnPORTESChanged();
    
        /// <summary>
        /// There are no comments for VALOREXP in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> VALOREXP
        {
            get
            {
                global::System.Nullable<decimal> value = _VALOREXP;
                OnGetVALOREXP(ref value);
                return value;
            }
            set
            {
                if (_VALOREXP != value)
                {
                  OnVALOREXPChanging(ref value);
                  ReportPropertyChanging("VALOREXP");
                  _VALOREXP = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("VALOREXP");
                  OnVALOREXPChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _VALOREXP;
        partial void OnGetVALOREXP(ref global::System.Nullable<decimal> value);
        partial void OnVALOREXPChanging(ref global::System.Nullable<decimal> value);
        partial void OnVALOREXPChanged();
    
        /// <summary>
        /// There are no comments for STATUSNR in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Required()]
        public bool STATUSNR
        {
            get
            {
                bool value = _STATUSNR;
                OnGetSTATUSNR(ref value);
                return value;
            }
            set
            {
                if (_STATUSNR != value)
                {
                  OnSTATUSNRChanging(ref value);
                  ReportPropertyChanging("STATUSNR");
                  _STATUSNR = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("STATUSNR");
                  OnSTATUSNRChanged();
              }
            }
        }
        private bool _STATUSNR;
        partial void OnGetSTATUSNR(ref bool value);
        partial void OnSTATUSNRChanging(ref bool value);
        partial void OnSTATUSNRChanged();
    
        /// <summary>
        /// There are no comments for COMENT1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(60)]
        public string COMENT1
        {
            get
            {
                string value = _COMENT1;
                OnGetCOMENT1(ref value);
                return value;
            }
            set
            {
                if (_COMENT1 != value)
                {
                  OnCOMENT1Changing(ref value);
                  ReportPropertyChanging("COMENT1");
                  _COMENT1 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("COMENT1");
                  OnCOMENT1Changed();
              }
            }
        }
        private string _COMENT1;
        partial void OnGetCOMENT1(ref string value);
        partial void OnCOMENT1Changing(ref string value);
        partial void OnCOMENT1Changed();
    
        /// <summary>
        /// There are no comments for COMENT2 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(60)]
        public string COMENT2
        {
            get
            {
                string value = _COMENT2;
                OnGetCOMENT2(ref value);
                return value;
            }
            set
            {
                if (_COMENT2 != value)
                {
                  OnCOMENT2Changing(ref value);
                  ReportPropertyChanging("COMENT2");
                  _COMENT2 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("COMENT2");
                  OnCOMENT2Changed();
              }
            }
        }
        private string _COMENT2;
        partial void OnGetCOMENT2(ref string value);
        partial void OnCOMENT2Changing(ref string value);
        partial void OnCOMENT2Changed();
    
        /// <summary>
        /// There are no comments for COMENT3 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(60)]
        public string COMENT3
        {
            get
            {
                string value = _COMENT3;
                OnGetCOMENT3(ref value);
                return value;
            }
            set
            {
                if (_COMENT3 != value)
                {
                  OnCOMENT3Changing(ref value);
                  ReportPropertyChanging("COMENT3");
                  _COMENT3 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("COMENT3");
                  OnCOMENT3Changed();
              }
            }
        }
        private string _COMENT3;
        partial void OnGetCOMENT3(ref string value);
        partial void OnCOMENT3Changing(ref string value);
        partial void OnCOMENT3Changed();
    
        /// <summary>
        /// There are no comments for COMENT4 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(60)]
        public string COMENT4
        {
            get
            {
                string value = _COMENT4;
                OnGetCOMENT4(ref value);
                return value;
            }
            set
            {
                if (_COMENT4 != value)
                {
                  OnCOMENT4Changing(ref value);
                  ReportPropertyChanging("COMENT4");
                  _COMENT4 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("COMENT4");
                  OnCOMENT4Changed();
              }
            }
        }
        private string _COMENT4;
        partial void OnGetCOMENT4(ref string value);
        partial void OnCOMENT4Changing(ref string value);
        partial void OnCOMENT4Changed();
    
        /// <summary>
        /// There are no comments for COMENT5 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(60)]
        public string COMENT5
        {
            get
            {
                string value = _COMENT5;
                OnGetCOMENT5(ref value);
                return value;
            }
            set
            {
                if (_COMENT5 != value)
                {
                  OnCOMENT5Changing(ref value);
                  ReportPropertyChanging("COMENT5");
                  _COMENT5 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("COMENT5");
                  OnCOMENT5Changed();
              }
            }
        }
        private string _COMENT5;
        partial void OnGetCOMENT5(ref string value);
        partial void OnCOMENT5Changing(ref string value);
        partial void OnCOMENT5Changed();
    
        /// <summary>
        /// There are no comments for COMENT6 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(60)]
        public string COMENT6
        {
            get
            {
                string value = _COMENT6;
                OnGetCOMENT6(ref value);
                return value;
            }
            set
            {
                if (_COMENT6 != value)
                {
                  OnCOMENT6Changing(ref value);
                  ReportPropertyChanging("COMENT6");
                  _COMENT6 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("COMENT6");
                  OnCOMENT6Changed();
              }
            }
        }
        private string _COMENT6;
        partial void OnGetCOMENT6(ref string value);
        partial void OnCOMENT6Changing(ref string value);
        partial void OnCOMENT6Changed();
    
        /// <summary>
        /// There are no comments for ENCOWEB in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<bool> ENCOWEB
        {
            get
            {
                global::System.Nullable<bool> value = _ENCOWEB;
                OnGetENCOWEB(ref value);
                return value;
            }
            set
            {
                if (_ENCOWEB != value)
                {
                  OnENCOWEBChanging(ref value);
                  ReportPropertyChanging("ENCOWEB");
                  _ENCOWEB = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("ENCOWEB");
                  OnENCOWEBChanged();
              }
            }
        }
        private global::System.Nullable<bool> _ENCOWEB;
        partial void OnGetENCOWEB(ref global::System.Nullable<bool> value);
        partial void OnENCOWEBChanging(ref global::System.Nullable<bool> value);
        partial void OnENCOWEBChanged();
    
        /// <summary>
        /// There are no comments for ESTADOWEB in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<byte> ESTADOWEB
        {
            get
            {
                global::System.Nullable<byte> value = _ESTADOWEB;
                OnGetESTADOWEB(ref value);
                return value;
            }
            set
            {
                if (_ESTADOWEB != value)
                {
                  OnESTADOWEBChanging(ref value);
                  ReportPropertyChanging("ESTADOWEB");
                  _ESTADOWEB = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("ESTADOWEB");
                  OnESTADOWEBChanged();
              }
            }
        }
        private global::System.Nullable<byte> _ESTADOWEB = 0;
        partial void OnGetESTADOWEB(ref global::System.Nullable<byte> value);
        partial void OnESTADOWEBChanging(ref global::System.Nullable<byte> value);
        partial void OnESTADOWEBChanged();
    
        /// <summary>
        /// There are no comments for UTILREGWEB in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string UTILREGWEB
        {
            get
            {
                string value = _UTILREGWEB;
                OnGetUTILREGWEB(ref value);
                return value;
            }
            set
            {
                if (_UTILREGWEB != value)
                {
                  OnUTILREGWEBChanging(ref value);
                  ReportPropertyChanging("UTILREGWEB");
                  _UTILREGWEB = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("UTILREGWEB");
                  OnUTILREGWEBChanged();
              }
            }
        }
        private string _UTILREGWEB = @"";
        partial void OnGetUTILREGWEB(ref string value);
        partial void OnUTILREGWEBChanging(ref string value);
        partial void OnUTILREGWEBChanged();
    
        /// <summary>
        /// There are no comments for SB_LINKMSG in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public string SB_LINKMSG
        {
            get
            {
                string value = _SB_LINKMSG;
                OnGetSB_LINKMSG(ref value);
                return value;
            }
            set
            {
                if (_SB_LINKMSG != value)
                {
                  OnSB_LINKMSGChanging(ref value);
                  ReportPropertyChanging("SB_LINKMSG");
                  _SB_LINKMSG = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("SB_LINKMSG");
                  OnSB_LINKMSGChanged();
              }
            }
        }
        private string _SB_LINKMSG;
        partial void OnGetSB_LINKMSG(ref string value);
        partial void OnSB_LINKMSGChanging(ref string value);
        partial void OnSB_LINKMSGChanged();
    
        /// <summary>
        /// There are no comments for CONFIRMADA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<bool> CONFIRMADA
        {
            get
            {
                global::System.Nullable<bool> value = _CONFIRMADA;
                OnGetCONFIRMADA(ref value);
                return value;
            }
            set
            {
                if (_CONFIRMADA != value)
                {
                  OnCONFIRMADAChanging(ref value);
                  ReportPropertyChanging("CONFIRMADA");
                  _CONFIRMADA = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("CONFIRMADA");
                  OnCONFIRMADAChanged();
              }
            }
        }
        private global::System.Nullable<bool> _CONFIRMADA;
        partial void OnGetCONFIRMADA(ref global::System.Nullable<bool> value);
        partial void OnCONFIRMADAChanging(ref global::System.Nullable<bool> value);
        partial void OnCONFIRMADAChanged();
    
        /// <summary>
        /// There are no comments for DATACONFIRM in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> DATACONFIRM
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _DATACONFIRM;
                OnGetDATACONFIRM(ref value);
                return value;
            }
            set
            {
                if (_DATACONFIRM != value)
                {
                  OnDATACONFIRMChanging(ref value);
                  ReportPropertyChanging("DATACONFIRM");
                  _DATACONFIRM = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DATACONFIRM");
                  OnDATACONFIRMChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _DATACONFIRM;
        partial void OnGetDATACONFIRM(ref global::System.Nullable<System.DateTime> value);
        partial void OnDATACONFIRMChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnDATACONFIRMChanged();
    
        /// <summary>
        /// There are no comments for SB_CONFIRMACAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(25)]
        public string SB_CONFIRMACAO
        {
            get
            {
                string value = _SB_CONFIRMACAO;
                OnGetSB_CONFIRMACAO(ref value);
                return value;
            }
            set
            {
                if (_SB_CONFIRMACAO != value)
                {
                  OnSB_CONFIRMACAOChanging(ref value);
                  ReportPropertyChanging("SB_CONFIRMACAO");
                  _SB_CONFIRMACAO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("SB_CONFIRMACAO");
                  OnSB_CONFIRMACAOChanged();
              }
            }
        }
        private string _SB_CONFIRMACAO;
        partial void OnGetSB_CONFIRMACAO(ref string value);
        partial void OnSB_CONFIRMACAOChanging(ref string value);
        partial void OnSB_CONFIRMACAOChanged();
    
        /// <summary>
        /// There are no comments for UTIL in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string UTIL
        {
            get
            {
                string value = _UTIL;
                OnGetUTIL(ref value);
                return value;
            }
            set
            {
                if (_UTIL != value)
                {
                  OnUTILChanging(ref value);
                  ReportPropertyChanging("UTIL");
                  _UTIL = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("UTIL");
                  OnUTILChanged();
              }
            }
        }
        private string _UTIL;
        partial void OnGetUTIL(ref string value);
        partial void OnUTILChanging(ref string value);
        partial void OnUTILChanged();
    
        /// <summary>
        /// There are no comments for ESTADO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(1)]
        public string ESTADO
        {
            get
            {
                string value = _ESTADO;
                OnGetESTADO(ref value);
                return value;
            }
            set
            {
                if (_ESTADO != value)
                {
                  OnESTADOChanging(ref value);
                  ReportPropertyChanging("ESTADO");
                  _ESTADO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("ESTADO");
                  OnESTADOChanged();
              }
            }
        }
        private string _ESTADO;
        partial void OnGetESTADO(ref string value);
        partial void OnESTADOChanging(ref string value);
        partial void OnESTADOChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for estacoes in the schema.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataGiic_LiagoModel", "FK_ENCO_estacoes", "estacoes")]
        public estacoes estacoes
        {
            get
            {
                return ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<estacoes>("DataGiic_LiagoModel.FK_ENCO_estacoes", "estacoes").Value;
            }
            set
            {
                ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<estacoes>("DataGiic_LiagoModel.FK_ENCO_estacoes", "estacoes").Value = value;
            }
        }
    
        /// <summary>
        /// There are no comments for estacoes in the schema.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<estacoes> estacoesReference
        {
            get
            {
                return ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<estacoes>("DataGiic_LiagoModel.FK_ENCO_estacoes", "estacoes");
            }
            set
            {
                if (value != null)
                {
                    ((IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<estacoes>("DataGiic_LiagoModel.FK_ENCO_estacoes", "estacoes", value);
                }
                else 
                {
                    ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<estacoes>("DataGiic_LiagoModel.FK_ENCO_estacoes", "estacoes").Value = null;
                }
            }
        }
    
        /// <summary>
        /// There are no comments for TABPAG in the schema.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataGiic_LiagoModel", "FK_ENCO_TABPAG", "TABPAG")]
        public TABPAG TABPAG
        {
            get
            {
                return ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TABPAG>("DataGiic_LiagoModel.FK_ENCO_TABPAG", "TABPAG").Value;
            }
            set
            {
                ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TABPAG>("DataGiic_LiagoModel.FK_ENCO_TABPAG", "TABPAG").Value = value;
            }
        }
    
        /// <summary>
        /// There are no comments for TABPAG in the schema.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TABPAG> TABPAGReference
        {
            get
            {
                return ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TABPAG>("DataGiic_LiagoModel.FK_ENCO_TABPAG", "TABPAG");
            }
            set
            {
                if (value != null)
                {
                    ((IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TABPAG>("DataGiic_LiagoModel.FK_ENCO_TABPAG", "TABPAG", value);
                }
                else 
                {
                    ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TABPAG>("DataGiic_LiagoModel.FK_ENCO_TABPAG", "TABPAG").Value = null;
                }
            }
        }
    
        /// <summary>
        /// There are no comments for TABCONTASBAN in the schema.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataGiic_LiagoModel", "FK_ENCO_TABCONTASBAN", "TABCONTASBAN")]
        public TABCONTASBAN TABCONTASBAN
        {
            get
            {
                return ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TABCONTASBAN>("DataGiic_LiagoModel.FK_ENCO_TABCONTASBAN", "TABCONTASBAN").Value;
            }
            set
            {
                ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TABCONTASBAN>("DataGiic_LiagoModel.FK_ENCO_TABCONTASBAN", "TABCONTASBAN").Value = value;
            }
        }
    
        /// <summary>
        /// There are no comments for TABCONTASBAN in the schema.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TABCONTASBAN> TABCONTASBANReference
        {
            get
            {
                return ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TABCONTASBAN>("DataGiic_LiagoModel.FK_ENCO_TABCONTASBAN", "TABCONTASBAN");
            }
            set
            {
                if (value != null)
                {
                    ((IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TABCONTASBAN>("DataGiic_LiagoModel.FK_ENCO_TABCONTASBAN", "TABCONTASBAN", value);
                }
                else 
                {
                    ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TABCONTASBAN>("DataGiic_LiagoModel.FK_ENCO_TABCONTASBAN", "TABCONTASBAN").Value = null;
                }
            }
        }
    
        /// <summary>
        /// There are no comments for CLIENTES in the schema.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataGiic_LiagoModel", "FK_ENCO_CLIENTES", "CLIENTES")]
        public CLIENTES CLIENTES
        {
            get
            {
                return ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CLIENTES>("DataGiic_LiagoModel.FK_ENCO_CLIENTES", "CLIENTES").Value;
            }
            set
            {
                ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CLIENTES>("DataGiic_LiagoModel.FK_ENCO_CLIENTES", "CLIENTES").Value = value;
            }
        }
    
        /// <summary>
        /// There are no comments for CLIENTES in the schema.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENTES> CLIENTESReference
        {
            get
            {
                return ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CLIENTES>("DataGiic_LiagoModel.FK_ENCO_CLIENTES", "CLIENTES");
            }
            set
            {
                if (value != null)
                {
                    ((IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CLIENTES>("DataGiic_LiagoModel.FK_ENCO_CLIENTES", "CLIENTES", value);
                }
                else 
                {
                    ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CLIENTES>("DataGiic_LiagoModel.FK_ENCO_CLIENTES", "CLIENTES").Value = null;
                }
            }
        }

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            ENCO obj = new ENCO();
            obj.NRENCO = NRENCO;
            obj.ENCOCLI = ENCOCLI;
            obj.CLIENTE = CLIENTE;
            obj.NRMORADA = NRMORADA;
            obj.ESTACAO = ESTACAO;
            obj.MARCA = MARCA;
            obj.GRIFO = GRIFO;
            obj.GRIFO_CARTAZ = GRIFO_CARTAZ;
            obj.GRIFO_CODCOR = GRIFO_CODCOR;
            obj.DATAENCO = DATAENCO;
            obj.PROCESSO = PROCESSO;
            obj.PRAZO = PRAZO;
            obj.MOEDA = MOEDA;
            obj.CAMBIO = CAMBIO;
            obj.CNDPAG = CNDPAG;
            obj.ID_CONTA = ID_CONTA;
            obj.AGENTE = AGENTE;
            obj.AGENTE1 = AGENTE1;
            obj.AGENTE2 = AGENTE2;
            obj.AGENTE3 = AGENTE3;
            obj.COMISSAO = COMISSAO;
            obj.COMISSAO1 = COMISSAO1;
            obj.COMISSAO2 = COMISSAO2;
            obj.COMISSAO3 = COMISSAO3;
            obj.CATALOGO = CATALOGO;
            obj.TARIFA = TARIFA;
            obj.COEF = COEF;
            obj.NRREGCAT = NRREGCAT;
            obj.CODMT = CODMT;
            obj.CODTRAN = CODTRAN;
            obj.TRANSIT = TRANSIT;
            obj.CNDENT = CNDENT;
            obj.DESC1 = DESC1;
            obj.DESC2 = DESC2;
            obj.DESC3 = DESC3;
            obj.TOTALENC = TOTALENC;
            obj.TOTALEXP = TOTALEXP;
            obj.TOTSALDO = TOTSALDO;
            obj.VALORENC = VALORENC;
            obj.TDESCLNENC = TDESCLNENC;
            obj.DESCONTOS = DESCONTOS;
            obj.PORTES = PORTES;
            obj.VALOREXP = VALOREXP;
            obj.STATUSNR = STATUSNR;
            obj.COMENT1 = COMENT1;
            obj.COMENT2 = COMENT2;
            obj.COMENT3 = COMENT3;
            obj.COMENT4 = COMENT4;
            obj.COMENT5 = COMENT5;
            obj.COMENT6 = COMENT6;
            obj.ENCOWEB = ENCOWEB;
            obj.ESTADOWEB = ESTADOWEB;
            obj.UTILREGWEB = UTILREGWEB;
            obj.SB_LINKMSG = SB_LINKMSG;
            obj.CONFIRMADA = CONFIRMADA;
            obj.DATACONFIRM = DATACONFIRM;
            obj.SB_CONFIRMACAO = SB_CONFIRMACAO;
            obj.UTIL = UTIL;
            obj.ESTADO = ESTADO;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          ENCO toCompare = obj as ENCO;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.NRENCO, toCompare.NRENCO))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + NRENCO.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
