//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.WK_PRINT_ENTID in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SPID
    /// CLIENTE
    /// TERCEIRO
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="WK_PRINT_ENTID")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WK_PRINT_ENTID : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new WK_PRINT_ENTID object.
        /// </summary>
        /// <param name="sPID">Initial value of SPID.</param>
        /// <param name="cLIENTE">Initial value of CLIENTE.</param>
        /// <param name="tERCEIRO">Initial value of TERCEIRO.</param>
        public static WK_PRINT_ENTID CreateWK_PRINT_ENTID(int sPID, string cLIENTE, string tERCEIRO)
        {
            WK_PRINT_ENTID wK_PRINT_ENTID = new WK_PRINT_ENTID();
            wK_PRINT_ENTID.SPID = sPID;
            wK_PRINT_ENTID.CLIENTE = cLIENTE;
            wK_PRINT_ENTID.TERCEIRO = tERCEIRO;
            return wK_PRINT_ENTID;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for SPID in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public int SPID
        {
            get
            {
                int value = _SPID;
                OnGetSPID(ref value);
                return value;
            }
            set
            {
                if (_SPID != value)
                {
                  OnSPIDChanging(ref value);
                  ReportPropertyChanging("SPID");
                  _SPID = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("SPID");
                  OnSPIDChanged();
              }
            }
        }
        private int _SPID;
        partial void OnGetSPID(ref int value);
        partial void OnSPIDChanging(ref int value);
        partial void OnSPIDChanged();
    
        /// <summary>
        /// There are no comments for CLIENTE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(5)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string CLIENTE
        {
            get
            {
                string value = _CLIENTE;
                OnGetCLIENTE(ref value);
                return value;
            }
            set
            {
                if (_CLIENTE != value)
                {
                  OnCLIENTEChanging(ref value);
                  ReportPropertyChanging("CLIENTE");
                  _CLIENTE = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("CLIENTE");
                  OnCLIENTEChanged();
              }
            }
        }
        private string _CLIENTE;
        partial void OnGetCLIENTE(ref string value);
        partial void OnCLIENTEChanging(ref string value);
        partial void OnCLIENTEChanged();
    
        /// <summary>
        /// There are no comments for TERCEIRO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(1)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string TERCEIRO
        {
            get
            {
                string value = _TERCEIRO;
                OnGetTERCEIRO(ref value);
                return value;
            }
            set
            {
                if (_TERCEIRO != value)
                {
                  OnTERCEIROChanging(ref value);
                  ReportPropertyChanging("TERCEIRO");
                  _TERCEIRO = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("TERCEIRO");
                  OnTERCEIROChanged();
              }
            }
        }
        private string _TERCEIRO;
        partial void OnGetTERCEIRO(ref string value);
        partial void OnTERCEIROChanging(ref string value);
        partial void OnTERCEIROChanged();
    
        /// <summary>
        /// There are no comments for NOME in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(45)]
        public string NOME
        {
            get
            {
                string value = _NOME;
                OnGetNOME(ref value);
                return value;
            }
            set
            {
                if (_NOME != value)
                {
                  OnNOMEChanging(ref value);
                  ReportPropertyChanging("NOME");
                  _NOME = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("NOME");
                  OnNOMEChanged();
              }
            }
        }
        private string _NOME;
        partial void OnGetNOME(ref string value);
        partial void OnNOMEChanging(ref string value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// There are no comments for QT in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> QT
        {
            get
            {
                global::System.Nullable<int> value = _QT;
                OnGetQT(ref value);
                return value;
            }
            set
            {
                if (_QT != value)
                {
                  OnQTChanging(ref value);
                  ReportPropertyChanging("QT");
                  _QT = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("QT");
                  OnQTChanged();
              }
            }
        }
        private global::System.Nullable<int> _QT = 1;
        partial void OnGetQT(ref global::System.Nullable<int> value);
        partial void OnQTChanging(ref global::System.Nullable<int> value);
        partial void OnQTChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            WK_PRINT_ENTID obj = new WK_PRINT_ENTID();
            obj.SPID = SPID;
            obj.CLIENTE = CLIENTE;
            obj.TERCEIRO = TERCEIRO;
            obj.NOME = NOME;
            obj.QT = QT;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          WK_PRINT_ENTID toCompare = obj as WK_PRINT_ENTID;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.SPID, toCompare.SPID))
            return false;
          if (!Object.Equals(this.CLIENTE, toCompare.CLIENTE))
            return false;
          if (!Object.Equals(this.TERCEIRO, toCompare.TERCEIRO))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + SPID.GetHashCode();
          hashCode = (hashCode * 7) + CLIENTE.GetHashCode();
          hashCode = (hashCode * 7) + TERCEIRO.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
