//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.PESSOAL in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODEMP
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="PESSOAL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PESSOAL : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new PESSOAL object.
        /// </summary>
        /// <param name="cODEMP">Initial value of CODEMP.</param>
        public static PESSOAL CreatePESSOAL(string cODEMP)
        {
            PESSOAL pESSOAL = new PESSOAL();
            pESSOAL.CODEMP = cODEMP;
            return pESSOAL;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for CODEMP in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string CODEMP
        {
            get
            {
                string value = _CODEMP;
                OnGetCODEMP(ref value);
                return value;
            }
            set
            {
                if (_CODEMP != value)
                {
                  OnCODEMPChanging(ref value);
                  ReportPropertyChanging("CODEMP");
                  _CODEMP = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("CODEMP");
                  OnCODEMPChanged();
              }
            }
        }
        private string _CODEMP;
        partial void OnGetCODEMP(ref string value);
        partial void OnCODEMPChanging(ref string value);
        partial void OnCODEMPChanged();
    
        /// <summary>
        /// There are no comments for NOME in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(35)]
        public string NOME
        {
            get
            {
                string value = _NOME;
                OnGetNOME(ref value);
                return value;
            }
            set
            {
                if (_NOME != value)
                {
                  OnNOMEChanging(ref value);
                  ReportPropertyChanging("NOME");
                  _NOME = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("NOME");
                  OnNOMEChanged();
              }
            }
        }
        private string _NOME;
        partial void OnGetNOME(ref string value);
        partial void OnNOMEChanging(ref string value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// There are no comments for SECCAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(6)]
        public string SECCAO
        {
            get
            {
                string value = _SECCAO;
                OnGetSECCAO(ref value);
                return value;
            }
            set
            {
                if (_SECCAO != value)
                {
                  OnSECCAOChanging(ref value);
                  ReportPropertyChanging("SECCAO");
                  _SECCAO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("SECCAO");
                  OnSECCAOChanged();
              }
            }
        }
        private string _SECCAO;
        partial void OnGetSECCAO(ref string value);
        partial void OnSECCAOChanging(ref string value);
        partial void OnSECCAOChanged();
    
        /// <summary>
        /// There are no comments for DATAINI in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> DATAINI
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _DATAINI;
                OnGetDATAINI(ref value);
                return value;
            }
            set
            {
                if (_DATAINI != value)
                {
                  OnDATAINIChanging(ref value);
                  ReportPropertyChanging("DATAINI");
                  _DATAINI = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DATAINI");
                  OnDATAINIChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _DATAINI;
        partial void OnGetDATAINI(ref global::System.Nullable<System.DateTime> value);
        partial void OnDATAINIChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnDATAINIChanged();
    
        /// <summary>
        /// There are no comments for CLASSE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string CLASSE
        {
            get
            {
                string value = _CLASSE;
                OnGetCLASSE(ref value);
                return value;
            }
            set
            {
                if (_CLASSE != value)
                {
                  OnCLASSEChanging(ref value);
                  ReportPropertyChanging("CLASSE");
                  _CLASSE = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("CLASSE");
                  OnCLASSEChanged();
              }
            }
        }
        private string _CLASSE;
        partial void OnGetCLASSE(ref string value);
        partial void OnCLASSEChanging(ref string value);
        partial void OnCLASSEChanged();
    
        /// <summary>
        /// There are no comments for cod_horario in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string cod_horario
        {
            get
            {
                string value = _cod_horario;
                OnGetcod_horario(ref value);
                return value;
            }
            set
            {
                if (_cod_horario != value)
                {
                  Oncod_horarioChanging(ref value);
                  ReportPropertyChanging("cod_horario");
                  _cod_horario = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("cod_horario");
                  Oncod_horarioChanged();
              }
            }
        }
        private string _cod_horario;
        partial void OnGetcod_horario(ref string value);
        partial void Oncod_horarioChanging(ref string value);
        partial void Oncod_horarioChanged();
    
        /// <summary>
        /// There are no comments for COMENT in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(40)]
        public string COMENT
        {
            get
            {
                string value = _COMENT;
                OnGetCOMENT(ref value);
                return value;
            }
            set
            {
                if (_COMENT != value)
                {
                  OnCOMENTChanging(ref value);
                  ReportPropertyChanging("COMENT");
                  _COMENT = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("COMENT");
                  OnCOMENTChanged();
              }
            }
        }
        private string _COMENT;
        partial void OnGetCOMENT(ref string value);
        partial void OnCOMENTChanging(ref string value);
        partial void OnCOMENTChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            PESSOAL obj = new PESSOAL();
            obj.CODEMP = CODEMP;
            obj.NOME = NOME;
            obj.SECCAO = SECCAO;
            obj.DATAINI = DATAINI;
            obj.CLASSE = CLASSE;
            obj.cod_horario = cod_horario;
            obj.COMENT = COMENT;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          PESSOAL toCompare = obj as PESSOAL;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.CODEMP, toCompare.CODEMP))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + CODEMP.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
