//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.PromocoesArtigos in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Arm
    /// Artigo
    /// DataInicio
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="PromocoesArtigos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PromocoesArtigos : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new PromocoesArtigos object.
        /// </summary>
        /// <param name="arm">Initial value of Arm.</param>
        /// <param name="artigo">Initial value of Artigo.</param>
        /// <param name="dataInicio">Initial value of DataInicio.</param>
        /// <param name="modelo">Initial value of Modelo.</param>
        /// <param name="variante">Initial value of Variante.</param>
        public static PromocoesArtigos CreatePromocoesArtigos(string arm, string artigo, global::System.DateTime dataInicio, string modelo, string variante)
        {
            PromocoesArtigos promocoesArtigos = new PromocoesArtigos();
            promocoesArtigos.Arm = arm;
            promocoesArtigos.Artigo = artigo;
            promocoesArtigos.DataInicio = dataInicio;
            promocoesArtigos.Modelo = modelo;
            promocoesArtigos.Variante = variante;
            return promocoesArtigos;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for Arm in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string Arm
        {
            get
            {
                string value = _Arm;
                OnGetArm(ref value);
                return value;
            }
            set
            {
                if (_Arm != value)
                {
                  OnArmChanging(ref value);
                  ReportPropertyChanging("Arm");
                  _Arm = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("Arm");
                  OnArmChanged();
              }
            }
        }
        private string _Arm;
        partial void OnGetArm(ref string value);
        partial void OnArmChanging(ref string value);
        partial void OnArmChanged();
    
        /// <summary>
        /// There are no comments for Artigo in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(12)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string Artigo
        {
            get
            {
                string value = _Artigo;
                OnGetArtigo(ref value);
                return value;
            }
            set
            {
                if (_Artigo != value)
                {
                  OnArtigoChanging(ref value);
                  ReportPropertyChanging("Artigo");
                  _Artigo = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("Artigo");
                  OnArtigoChanged();
              }
            }
        }
        private string _Artigo;
        partial void OnGetArtigo(ref string value);
        partial void OnArtigoChanging(ref string value);
        partial void OnArtigoChanged();
    
        /// <summary>
        /// There are no comments for DataInicio in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public global::System.DateTime DataInicio
        {
            get
            {
                global::System.DateTime value = _DataInicio;
                OnGetDataInicio(ref value);
                return value;
            }
            set
            {
                if (_DataInicio != value)
                {
                  OnDataInicioChanging(ref value);
                  ReportPropertyChanging("DataInicio");
                  _DataInicio = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DataInicio");
                  OnDataInicioChanged();
              }
            }
        }
        private global::System.DateTime _DataInicio;
        partial void OnGetDataInicio(ref global::System.DateTime value);
        partial void OnDataInicioChanging(ref global::System.DateTime value);
        partial void OnDataInicioChanged();
    
        /// <summary>
        /// There are no comments for Modelo in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(10)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string Modelo
        {
            get
            {
                string value = _Modelo;
                OnGetModelo(ref value);
                return value;
            }
            set
            {
                if (_Modelo != value)
                {
                  OnModeloChanging(ref value);
                  ReportPropertyChanging("Modelo");
                  _Modelo = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("Modelo");
                  OnModeloChanged();
              }
            }
        }
        private string _Modelo = @"";
        partial void OnGetModelo(ref string value);
        partial void OnModeloChanging(ref string value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// There are no comments for Variante in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string Variante
        {
            get
            {
                string value = _Variante;
                OnGetVariante(ref value);
                return value;
            }
            set
            {
                if (_Variante != value)
                {
                  OnVarianteChanging(ref value);
                  ReportPropertyChanging("Variante");
                  _Variante = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("Variante");
                  OnVarianteChanged();
              }
            }
        }
        private string _Variante = @"";
        partial void OnGetVariante(ref string value);
        partial void OnVarianteChanging(ref string value);
        partial void OnVarianteChanged();
    
        /// <summary>
        /// There are no comments for Cod_Promo in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> Cod_Promo
        {
            get
            {
                global::System.Nullable<int> value = _Cod_Promo;
                OnGetCod_Promo(ref value);
                return value;
            }
            set
            {
                if (_Cod_Promo != value)
                {
                  OnCod_PromoChanging(ref value);
                  ReportPropertyChanging("Cod_Promo");
                  _Cod_Promo = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Cod_Promo");
                  OnCod_PromoChanged();
              }
            }
        }
        private global::System.Nullable<int> _Cod_Promo;
        partial void OnGetCod_Promo(ref global::System.Nullable<int> value);
        partial void OnCod_PromoChanging(ref global::System.Nullable<int> value);
        partial void OnCod_PromoChanged();
    
        /// <summary>
        /// There are no comments for Escala in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string Escala
        {
            get
            {
                string value = _Escala;
                OnGetEscala(ref value);
                return value;
            }
            set
            {
                if (_Escala != value)
                {
                  OnEscalaChanging(ref value);
                  ReportPropertyChanging("Escala");
                  _Escala = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Escala");
                  OnEscalaChanged();
              }
            }
        }
        private string _Escala = @"";
        partial void OnGetEscala(ref string value);
        partial void OnEscalaChanging(ref string value);
        partial void OnEscalaChanged();
    
        /// <summary>
        /// There are no comments for IDOTAM1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IDOTAM1
        {
            get
            {
                global::System.Nullable<int> value = _IDOTAM1;
                OnGetIDOTAM1(ref value);
                return value;
            }
            set
            {
                if (_IDOTAM1 != value)
                {
                  OnIDOTAM1Changing(ref value);
                  ReportPropertyChanging("IDOTAM1");
                  _IDOTAM1 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IDOTAM1");
                  OnIDOTAM1Changed();
              }
            }
        }
        private global::System.Nullable<int> _IDOTAM1;
        partial void OnGetIDOTAM1(ref global::System.Nullable<int> value);
        partial void OnIDOTAM1Changing(ref global::System.Nullable<int> value);
        partial void OnIDOTAM1Changed();
    
        /// <summary>
        /// There are no comments for IAOTAM1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IAOTAM1
        {
            get
            {
                global::System.Nullable<int> value = _IAOTAM1;
                OnGetIAOTAM1(ref value);
                return value;
            }
            set
            {
                if (_IAOTAM1 != value)
                {
                  OnIAOTAM1Changing(ref value);
                  ReportPropertyChanging("IAOTAM1");
                  _IAOTAM1 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IAOTAM1");
                  OnIAOTAM1Changed();
              }
            }
        }
        private global::System.Nullable<int> _IAOTAM1;
        partial void OnGetIAOTAM1(ref global::System.Nullable<int> value);
        partial void OnIAOTAM1Changing(ref global::System.Nullable<int> value);
        partial void OnIAOTAM1Changed();
    
        /// <summary>
        /// There are no comments for DOTAM1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string DOTAM1
        {
            get
            {
                string value = _DOTAM1;
                OnGetDOTAM1(ref value);
                return value;
            }
            set
            {
                if (_DOTAM1 != value)
                {
                  OnDOTAM1Changing(ref value);
                  ReportPropertyChanging("DOTAM1");
                  _DOTAM1 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DOTAM1");
                  OnDOTAM1Changed();
              }
            }
        }
        private string _DOTAM1;
        partial void OnGetDOTAM1(ref string value);
        partial void OnDOTAM1Changing(ref string value);
        partial void OnDOTAM1Changed();
    
        /// <summary>
        /// There are no comments for AOTAM1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string AOTAM1
        {
            get
            {
                string value = _AOTAM1;
                OnGetAOTAM1(ref value);
                return value;
            }
            set
            {
                if (_AOTAM1 != value)
                {
                  OnAOTAM1Changing(ref value);
                  ReportPropertyChanging("AOTAM1");
                  _AOTAM1 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("AOTAM1");
                  OnAOTAM1Changed();
              }
            }
        }
        private string _AOTAM1;
        partial void OnGetAOTAM1(ref string value);
        partial void OnAOTAM1Changing(ref string value);
        partial void OnAOTAM1Changed();
    
        /// <summary>
        /// There are no comments for IDOTAM2 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IDOTAM2
        {
            get
            {
                global::System.Nullable<int> value = _IDOTAM2;
                OnGetIDOTAM2(ref value);
                return value;
            }
            set
            {
                if (_IDOTAM2 != value)
                {
                  OnIDOTAM2Changing(ref value);
                  ReportPropertyChanging("IDOTAM2");
                  _IDOTAM2 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IDOTAM2");
                  OnIDOTAM2Changed();
              }
            }
        }
        private global::System.Nullable<int> _IDOTAM2;
        partial void OnGetIDOTAM2(ref global::System.Nullable<int> value);
        partial void OnIDOTAM2Changing(ref global::System.Nullable<int> value);
        partial void OnIDOTAM2Changed();
    
        /// <summary>
        /// There are no comments for IAOTAM2 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IAOTAM2
        {
            get
            {
                global::System.Nullable<int> value = _IAOTAM2;
                OnGetIAOTAM2(ref value);
                return value;
            }
            set
            {
                if (_IAOTAM2 != value)
                {
                  OnIAOTAM2Changing(ref value);
                  ReportPropertyChanging("IAOTAM2");
                  _IAOTAM2 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IAOTAM2");
                  OnIAOTAM2Changed();
              }
            }
        }
        private global::System.Nullable<int> _IAOTAM2;
        partial void OnGetIAOTAM2(ref global::System.Nullable<int> value);
        partial void OnIAOTAM2Changing(ref global::System.Nullable<int> value);
        partial void OnIAOTAM2Changed();
    
        /// <summary>
        /// There are no comments for DOTAM2 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string DOTAM2
        {
            get
            {
                string value = _DOTAM2;
                OnGetDOTAM2(ref value);
                return value;
            }
            set
            {
                if (_DOTAM2 != value)
                {
                  OnDOTAM2Changing(ref value);
                  ReportPropertyChanging("DOTAM2");
                  _DOTAM2 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DOTAM2");
                  OnDOTAM2Changed();
              }
            }
        }
        private string _DOTAM2;
        partial void OnGetDOTAM2(ref string value);
        partial void OnDOTAM2Changing(ref string value);
        partial void OnDOTAM2Changed();
    
        /// <summary>
        /// There are no comments for AOTAM2 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string AOTAM2
        {
            get
            {
                string value = _AOTAM2;
                OnGetAOTAM2(ref value);
                return value;
            }
            set
            {
                if (_AOTAM2 != value)
                {
                  OnAOTAM2Changing(ref value);
                  ReportPropertyChanging("AOTAM2");
                  _AOTAM2 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("AOTAM2");
                  OnAOTAM2Changed();
              }
            }
        }
        private string _AOTAM2;
        partial void OnGetAOTAM2(ref string value);
        partial void OnAOTAM2Changing(ref string value);
        partial void OnAOTAM2Changed();
    
        /// <summary>
        /// There are no comments for IDOTAM3 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IDOTAM3
        {
            get
            {
                global::System.Nullable<int> value = _IDOTAM3;
                OnGetIDOTAM3(ref value);
                return value;
            }
            set
            {
                if (_IDOTAM3 != value)
                {
                  OnIDOTAM3Changing(ref value);
                  ReportPropertyChanging("IDOTAM3");
                  _IDOTAM3 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IDOTAM3");
                  OnIDOTAM3Changed();
              }
            }
        }
        private global::System.Nullable<int> _IDOTAM3;
        partial void OnGetIDOTAM3(ref global::System.Nullable<int> value);
        partial void OnIDOTAM3Changing(ref global::System.Nullable<int> value);
        partial void OnIDOTAM3Changed();
    
        /// <summary>
        /// There are no comments for IAOTAM3 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IAOTAM3
        {
            get
            {
                global::System.Nullable<int> value = _IAOTAM3;
                OnGetIAOTAM3(ref value);
                return value;
            }
            set
            {
                if (_IAOTAM3 != value)
                {
                  OnIAOTAM3Changing(ref value);
                  ReportPropertyChanging("IAOTAM3");
                  _IAOTAM3 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IAOTAM3");
                  OnIAOTAM3Changed();
              }
            }
        }
        private global::System.Nullable<int> _IAOTAM3;
        partial void OnGetIAOTAM3(ref global::System.Nullable<int> value);
        partial void OnIAOTAM3Changing(ref global::System.Nullable<int> value);
        partial void OnIAOTAM3Changed();
    
        /// <summary>
        /// There are no comments for DOTAM3 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string DOTAM3
        {
            get
            {
                string value = _DOTAM3;
                OnGetDOTAM3(ref value);
                return value;
            }
            set
            {
                if (_DOTAM3 != value)
                {
                  OnDOTAM3Changing(ref value);
                  ReportPropertyChanging("DOTAM3");
                  _DOTAM3 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DOTAM3");
                  OnDOTAM3Changed();
              }
            }
        }
        private string _DOTAM3;
        partial void OnGetDOTAM3(ref string value);
        partial void OnDOTAM3Changing(ref string value);
        partial void OnDOTAM3Changed();
    
        /// <summary>
        /// There are no comments for AOTAM3 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string AOTAM3
        {
            get
            {
                string value = _AOTAM3;
                OnGetAOTAM3(ref value);
                return value;
            }
            set
            {
                if (_AOTAM3 != value)
                {
                  OnAOTAM3Changing(ref value);
                  ReportPropertyChanging("AOTAM3");
                  _AOTAM3 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("AOTAM3");
                  OnAOTAM3Changed();
              }
            }
        }
        private string _AOTAM3;
        partial void OnGetAOTAM3(ref string value);
        partial void OnAOTAM3Changing(ref string value);
        partial void OnAOTAM3Changed();
    
        /// <summary>
        /// There are no comments for IDOTAM4 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IDOTAM4
        {
            get
            {
                global::System.Nullable<int> value = _IDOTAM4;
                OnGetIDOTAM4(ref value);
                return value;
            }
            set
            {
                if (_IDOTAM4 != value)
                {
                  OnIDOTAM4Changing(ref value);
                  ReportPropertyChanging("IDOTAM4");
                  _IDOTAM4 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IDOTAM4");
                  OnIDOTAM4Changed();
              }
            }
        }
        private global::System.Nullable<int> _IDOTAM4;
        partial void OnGetIDOTAM4(ref global::System.Nullable<int> value);
        partial void OnIDOTAM4Changing(ref global::System.Nullable<int> value);
        partial void OnIDOTAM4Changed();
    
        /// <summary>
        /// There are no comments for IAOTAM4 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IAOTAM4
        {
            get
            {
                global::System.Nullable<int> value = _IAOTAM4;
                OnGetIAOTAM4(ref value);
                return value;
            }
            set
            {
                if (_IAOTAM4 != value)
                {
                  OnIAOTAM4Changing(ref value);
                  ReportPropertyChanging("IAOTAM4");
                  _IAOTAM4 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IAOTAM4");
                  OnIAOTAM4Changed();
              }
            }
        }
        private global::System.Nullable<int> _IAOTAM4;
        partial void OnGetIAOTAM4(ref global::System.Nullable<int> value);
        partial void OnIAOTAM4Changing(ref global::System.Nullable<int> value);
        partial void OnIAOTAM4Changed();
    
        /// <summary>
        /// There are no comments for DOTAM4 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string DOTAM4
        {
            get
            {
                string value = _DOTAM4;
                OnGetDOTAM4(ref value);
                return value;
            }
            set
            {
                if (_DOTAM4 != value)
                {
                  OnDOTAM4Changing(ref value);
                  ReportPropertyChanging("DOTAM4");
                  _DOTAM4 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DOTAM4");
                  OnDOTAM4Changed();
              }
            }
        }
        private string _DOTAM4;
        partial void OnGetDOTAM4(ref string value);
        partial void OnDOTAM4Changing(ref string value);
        partial void OnDOTAM4Changed();
    
        /// <summary>
        /// There are no comments for AOTAM4 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string AOTAM4
        {
            get
            {
                string value = _AOTAM4;
                OnGetAOTAM4(ref value);
                return value;
            }
            set
            {
                if (_AOTAM4 != value)
                {
                  OnAOTAM4Changing(ref value);
                  ReportPropertyChanging("AOTAM4");
                  _AOTAM4 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("AOTAM4");
                  OnAOTAM4Changed();
              }
            }
        }
        private string _AOTAM4;
        partial void OnGetAOTAM4(ref string value);
        partial void OnAOTAM4Changing(ref string value);
        partial void OnAOTAM4Changed();
    
        /// <summary>
        /// There are no comments for IDOTAM5 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IDOTAM5
        {
            get
            {
                global::System.Nullable<int> value = _IDOTAM5;
                OnGetIDOTAM5(ref value);
                return value;
            }
            set
            {
                if (_IDOTAM5 != value)
                {
                  OnIDOTAM5Changing(ref value);
                  ReportPropertyChanging("IDOTAM5");
                  _IDOTAM5 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IDOTAM5");
                  OnIDOTAM5Changed();
              }
            }
        }
        private global::System.Nullable<int> _IDOTAM5;
        partial void OnGetIDOTAM5(ref global::System.Nullable<int> value);
        partial void OnIDOTAM5Changing(ref global::System.Nullable<int> value);
        partial void OnIDOTAM5Changed();
    
        /// <summary>
        /// There are no comments for IAOTAM5 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> IAOTAM5
        {
            get
            {
                global::System.Nullable<int> value = _IAOTAM5;
                OnGetIAOTAM5(ref value);
                return value;
            }
            set
            {
                if (_IAOTAM5 != value)
                {
                  OnIAOTAM5Changing(ref value);
                  ReportPropertyChanging("IAOTAM5");
                  _IAOTAM5 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IAOTAM5");
                  OnIAOTAM5Changed();
              }
            }
        }
        private global::System.Nullable<int> _IAOTAM5;
        partial void OnGetIAOTAM5(ref global::System.Nullable<int> value);
        partial void OnIAOTAM5Changing(ref global::System.Nullable<int> value);
        partial void OnIAOTAM5Changed();
    
        /// <summary>
        /// There are no comments for DOTAM5 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string DOTAM5
        {
            get
            {
                string value = _DOTAM5;
                OnGetDOTAM5(ref value);
                return value;
            }
            set
            {
                if (_DOTAM5 != value)
                {
                  OnDOTAM5Changing(ref value);
                  ReportPropertyChanging("DOTAM5");
                  _DOTAM5 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DOTAM5");
                  OnDOTAM5Changed();
              }
            }
        }
        private string _DOTAM5;
        partial void OnGetDOTAM5(ref string value);
        partial void OnDOTAM5Changing(ref string value);
        partial void OnDOTAM5Changed();
    
        /// <summary>
        /// There are no comments for AOTAM5 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string AOTAM5
        {
            get
            {
                string value = _AOTAM5;
                OnGetAOTAM5(ref value);
                return value;
            }
            set
            {
                if (_AOTAM5 != value)
                {
                  OnAOTAM5Changing(ref value);
                  ReportPropertyChanging("AOTAM5");
                  _AOTAM5 = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("AOTAM5");
                  OnAOTAM5Changed();
              }
            }
        }
        private string _AOTAM5;
        partial void OnGetAOTAM5(ref string value);
        partial void OnAOTAM5Changing(ref string value);
        partial void OnAOTAM5Changed();
    
        /// <summary>
        /// There are no comments for PRECOP1 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<double> PRECOP1
        {
            get
            {
                global::System.Nullable<double> value = _PRECOP1;
                OnGetPRECOP1(ref value);
                return value;
            }
            set
            {
                if (_PRECOP1 != value)
                {
                  OnPRECOP1Changing(ref value);
                  ReportPropertyChanging("PRECOP1");
                  _PRECOP1 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PRECOP1");
                  OnPRECOP1Changed();
              }
            }
        }
        private global::System.Nullable<double> _PRECOP1;
        partial void OnGetPRECOP1(ref global::System.Nullable<double> value);
        partial void OnPRECOP1Changing(ref global::System.Nullable<double> value);
        partial void OnPRECOP1Changed();
    
        /// <summary>
        /// There are no comments for PRECOP2 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<double> PRECOP2
        {
            get
            {
                global::System.Nullable<double> value = _PRECOP2;
                OnGetPRECOP2(ref value);
                return value;
            }
            set
            {
                if (_PRECOP2 != value)
                {
                  OnPRECOP2Changing(ref value);
                  ReportPropertyChanging("PRECOP2");
                  _PRECOP2 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PRECOP2");
                  OnPRECOP2Changed();
              }
            }
        }
        private global::System.Nullable<double> _PRECOP2;
        partial void OnGetPRECOP2(ref global::System.Nullable<double> value);
        partial void OnPRECOP2Changing(ref global::System.Nullable<double> value);
        partial void OnPRECOP2Changed();
    
        /// <summary>
        /// There are no comments for PRECOP3 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<double> PRECOP3
        {
            get
            {
                global::System.Nullable<double> value = _PRECOP3;
                OnGetPRECOP3(ref value);
                return value;
            }
            set
            {
                if (_PRECOP3 != value)
                {
                  OnPRECOP3Changing(ref value);
                  ReportPropertyChanging("PRECOP3");
                  _PRECOP3 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PRECOP3");
                  OnPRECOP3Changed();
              }
            }
        }
        private global::System.Nullable<double> _PRECOP3;
        partial void OnGetPRECOP3(ref global::System.Nullable<double> value);
        partial void OnPRECOP3Changing(ref global::System.Nullable<double> value);
        partial void OnPRECOP3Changed();
    
        /// <summary>
        /// There are no comments for PRECOP4 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<double> PRECOP4
        {
            get
            {
                global::System.Nullable<double> value = _PRECOP4;
                OnGetPRECOP4(ref value);
                return value;
            }
            set
            {
                if (_PRECOP4 != value)
                {
                  OnPRECOP4Changing(ref value);
                  ReportPropertyChanging("PRECOP4");
                  _PRECOP4 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PRECOP4");
                  OnPRECOP4Changed();
              }
            }
        }
        private global::System.Nullable<double> _PRECOP4;
        partial void OnGetPRECOP4(ref global::System.Nullable<double> value);
        partial void OnPRECOP4Changing(ref global::System.Nullable<double> value);
        partial void OnPRECOP4Changed();
    
        /// <summary>
        /// There are no comments for PRECOP5 in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<double> PRECOP5
        {
            get
            {
                global::System.Nullable<double> value = _PRECOP5;
                OnGetPRECOP5(ref value);
                return value;
            }
            set
            {
                if (_PRECOP5 != value)
                {
                  OnPRECOP5Changing(ref value);
                  ReportPropertyChanging("PRECOP5");
                  _PRECOP5 = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PRECOP5");
                  OnPRECOP5Changed();
              }
            }
        }
        private global::System.Nullable<double> _PRECOP5;
        partial void OnGetPRECOP5(ref global::System.Nullable<double> value);
        partial void OnPRECOP5Changing(ref global::System.Nullable<double> value);
        partial void OnPRECOP5Changed();
    
        /// <summary>
        /// There are no comments for PREC in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> PREC
        {
            get
            {
                global::System.Nullable<decimal> value = _PREC;
                OnGetPREC(ref value);
                return value;
            }
            set
            {
                if (_PREC != value)
                {
                  OnPRECChanging(ref value);
                  ReportPropertyChanging("PREC");
                  _PREC = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("PREC");
                  OnPRECChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _PREC = 0m;
        partial void OnGetPREC(ref global::System.Nullable<decimal> value);
        partial void OnPRECChanging(ref global::System.Nullable<decimal> value);
        partial void OnPRECChanged();
    
        /// <summary>
        /// There are no comments for Activa in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<bool> Activa
        {
            get
            {
                global::System.Nullable<bool> value = _Activa;
                OnGetActiva(ref value);
                return value;
            }
            set
            {
                if (_Activa != value)
                {
                  OnActivaChanging(ref value);
                  ReportPropertyChanging("Activa");
                  _Activa = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Activa");
                  OnActivaChanged();
              }
            }
        }
        private global::System.Nullable<bool> _Activa;
        partial void OnGetActiva(ref global::System.Nullable<bool> value);
        partial void OnActivaChanging(ref global::System.Nullable<bool> value);
        partial void OnActivaChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            PromocoesArtigos obj = new PromocoesArtigos();
            obj.Arm = Arm;
            obj.Artigo = Artigo;
            obj.DataInicio = DataInicio;
            obj.Modelo = Modelo;
            obj.Variante = Variante;
            obj.Cod_Promo = Cod_Promo;
            obj.Escala = Escala;
            obj.IDOTAM1 = IDOTAM1;
            obj.IAOTAM1 = IAOTAM1;
            obj.DOTAM1 = DOTAM1;
            obj.AOTAM1 = AOTAM1;
            obj.IDOTAM2 = IDOTAM2;
            obj.IAOTAM2 = IAOTAM2;
            obj.DOTAM2 = DOTAM2;
            obj.AOTAM2 = AOTAM2;
            obj.IDOTAM3 = IDOTAM3;
            obj.IAOTAM3 = IAOTAM3;
            obj.DOTAM3 = DOTAM3;
            obj.AOTAM3 = AOTAM3;
            obj.IDOTAM4 = IDOTAM4;
            obj.IAOTAM4 = IAOTAM4;
            obj.DOTAM4 = DOTAM4;
            obj.AOTAM4 = AOTAM4;
            obj.IDOTAM5 = IDOTAM5;
            obj.IAOTAM5 = IAOTAM5;
            obj.DOTAM5 = DOTAM5;
            obj.AOTAM5 = AOTAM5;
            obj.PRECOP1 = PRECOP1;
            obj.PRECOP2 = PRECOP2;
            obj.PRECOP3 = PRECOP3;
            obj.PRECOP4 = PRECOP4;
            obj.PRECOP5 = PRECOP5;
            obj.PREC = PREC;
            obj.Activa = Activa;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          PromocoesArtigos toCompare = obj as PromocoesArtigos;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Arm, toCompare.Arm))
            return false;
          if (!Object.Equals(this.Artigo, toCompare.Artigo))
            return false;
          if (!Object.Equals(this.DataInicio, toCompare.DataInicio))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Arm.GetHashCode();
          hashCode = (hashCode * 7) + Artigo.GetHashCode();
          hashCode = (hashCode * 7) + DataInicio.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
