//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.mrp_oper in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Order_Id
    /// Department_id
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="mrp_oper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mrp_oper : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new mrp_oper object.
        /// </summary>
        /// <param name="order_Id">Initial value of Order_Id.</param>
        /// <param name="department_id">Initial value of Department_id.</param>
        public static mrp_oper Createmrp_oper(int order_Id, int department_id)
        {
            mrp_oper mrp_oper = new mrp_oper();
            mrp_oper.Order_Id = order_Id;
            mrp_oper.Department_id = department_id;
            return mrp_oper;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for Order_Id in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public int Order_Id
        {
            get
            {
                int value = _Order_Id;
                OnGetOrder_Id(ref value);
                return value;
            }
            set
            {
                if (_Order_Id != value)
                {
                  OnOrder_IdChanging(ref value);
                  ReportPropertyChanging("Order_Id");
                  _Order_Id = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Order_Id");
                  OnOrder_IdChanged();
              }
            }
        }
        private int _Order_Id;
        partial void OnGetOrder_Id(ref int value);
        partial void OnOrder_IdChanging(ref int value);
        partial void OnOrder_IdChanged();
    
        /// <summary>
        /// There are no comments for Department_id in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public int Department_id
        {
            get
            {
                int value = _Department_id;
                OnGetDepartment_id(ref value);
                return value;
            }
            set
            {
                if (_Department_id != value)
                {
                  OnDepartment_idChanging(ref value);
                  ReportPropertyChanging("Department_id");
                  _Department_id = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Department_id");
                  OnDepartment_idChanged();
              }
            }
        }
        private int _Department_id;
        partial void OnGetDepartment_id(ref int value);
        partial void OnDepartment_idChanging(ref int value);
        partial void OnDepartment_idChanged();
    
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string Department
        {
            get
            {
                string value = _Department;
                OnGetDepartment(ref value);
                return value;
            }
            set
            {
                if (_Department != value)
                {
                  OnDepartmentChanging(ref value);
                  ReportPropertyChanging("Department");
                  _Department = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Department");
                  OnDepartmentChanged();
              }
            }
        }
        private string _Department;
        partial void OnGetDepartment(ref string value);
        partial void OnDepartmentChanging(ref string value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// There are no comments for Release_min in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> Release_min
        {
            get
            {
                global::System.Nullable<int> value = _Release_min;
                OnGetRelease_min(ref value);
                return value;
            }
            set
            {
                if (_Release_min != value)
                {
                  OnRelease_minChanging(ref value);
                  ReportPropertyChanging("Release_min");
                  _Release_min = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Release_min");
                  OnRelease_minChanged();
              }
            }
        }
        private global::System.Nullable<int> _Release_min;
        partial void OnGetRelease_min(ref global::System.Nullable<int> value);
        partial void OnRelease_minChanging(ref global::System.Nullable<int> value);
        partial void OnRelease_minChanged();
    
        /// <summary>
        /// There are no comments for Release_mostlikely in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> Release_mostlikely
        {
            get
            {
                global::System.Nullable<int> value = _Release_mostlikely;
                OnGetRelease_mostlikely(ref value);
                return value;
            }
            set
            {
                if (_Release_mostlikely != value)
                {
                  OnRelease_mostlikelyChanging(ref value);
                  ReportPropertyChanging("Release_mostlikely");
                  _Release_mostlikely = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Release_mostlikely");
                  OnRelease_mostlikelyChanged();
              }
            }
        }
        private global::System.Nullable<int> _Release_mostlikely;
        partial void OnGetRelease_mostlikely(ref global::System.Nullable<int> value);
        partial void OnRelease_mostlikelyChanging(ref global::System.Nullable<int> value);
        partial void OnRelease_mostlikelyChanged();
    
        /// <summary>
        /// There are no comments for Release_max in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> Release_max
        {
            get
            {
                global::System.Nullable<int> value = _Release_max;
                OnGetRelease_max(ref value);
                return value;
            }
            set
            {
                if (_Release_max != value)
                {
                  OnRelease_maxChanging(ref value);
                  ReportPropertyChanging("Release_max");
                  _Release_max = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Release_max");
                  OnRelease_maxChanged();
              }
            }
        }
        private global::System.Nullable<int> _Release_max;
        partial void OnGetRelease_max(ref global::System.Nullable<int> value);
        partial void OnRelease_maxChanging(ref global::System.Nullable<int> value);
        partial void OnRelease_maxChanged();
    
        /// <summary>
        /// There are no comments for Release_data in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> Release_data
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _Release_data;
                OnGetRelease_data(ref value);
                return value;
            }
            set
            {
                if (_Release_data != value)
                {
                  OnRelease_dataChanging(ref value);
                  ReportPropertyChanging("Release_data");
                  _Release_data = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Release_data");
                  OnRelease_dataChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _Release_data;
        partial void OnGetRelease_data(ref global::System.Nullable<System.DateTime> value);
        partial void OnRelease_dataChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnRelease_dataChanged();
    
        /// <summary>
        /// There are no comments for Process_min in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> Process_min
        {
            get
            {
                global::System.Nullable<decimal> value = _Process_min;
                OnGetProcess_min(ref value);
                return value;
            }
            set
            {
                if (_Process_min != value)
                {
                  OnProcess_minChanging(ref value);
                  ReportPropertyChanging("Process_min");
                  _Process_min = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Process_min");
                  OnProcess_minChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _Process_min;
        partial void OnGetProcess_min(ref global::System.Nullable<decimal> value);
        partial void OnProcess_minChanging(ref global::System.Nullable<decimal> value);
        partial void OnProcess_minChanged();
    
        /// <summary>
        /// There are no comments for Process_mostlikely in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> Process_mostlikely
        {
            get
            {
                global::System.Nullable<decimal> value = _Process_mostlikely;
                OnGetProcess_mostlikely(ref value);
                return value;
            }
            set
            {
                if (_Process_mostlikely != value)
                {
                  OnProcess_mostlikelyChanging(ref value);
                  ReportPropertyChanging("Process_mostlikely");
                  _Process_mostlikely = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Process_mostlikely");
                  OnProcess_mostlikelyChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _Process_mostlikely;
        partial void OnGetProcess_mostlikely(ref global::System.Nullable<decimal> value);
        partial void OnProcess_mostlikelyChanging(ref global::System.Nullable<decimal> value);
        partial void OnProcess_mostlikelyChanged();
    
        /// <summary>
        /// There are no comments for Process_max in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> Process_max
        {
            get
            {
                global::System.Nullable<decimal> value = _Process_max;
                OnGetProcess_max(ref value);
                return value;
            }
            set
            {
                if (_Process_max != value)
                {
                  OnProcess_maxChanging(ref value);
                  ReportPropertyChanging("Process_max");
                  _Process_max = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Process_max");
                  OnProcess_maxChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _Process_max;
        partial void OnGetProcess_max(ref global::System.Nullable<decimal> value);
        partial void OnProcess_maxChanging(ref global::System.Nullable<decimal> value);
        partial void OnProcess_maxChanged();
    
        /// <summary>
        /// There are no comments for tipo in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public string tipo
        {
            get
            {
                string value = _tipo;
                OnGettipo(ref value);
                return value;
            }
            set
            {
                if (_tipo != value)
                {
                  OntipoChanging(ref value);
                  ReportPropertyChanging("tipo");
                  _tipo = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("tipo");
                  OntipoChanged();
              }
            }
        }
        private string _tipo;
        partial void OnGettipo(ref string value);
        partial void OntipoChanging(ref string value);
        partial void OntipoChanged();
    
        /// <summary>
        /// There are no comments for nrenco in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(6)]
        public string nrenco
        {
            get
            {
                string value = _nrenco;
                OnGetnrenco(ref value);
                return value;
            }
            set
            {
                if (_nrenco != value)
                {
                  OnnrencoChanging(ref value);
                  ReportPropertyChanging("nrenco");
                  _nrenco = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("nrenco");
                  OnnrencoChanged();
              }
            }
        }
        private string _nrenco;
        partial void OnGetnrenco(ref string value);
        partial void OnnrencoChanging(ref string value);
        partial void OnnrencoChanged();
    
        /// <summary>
        /// There are no comments for lnenco in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> lnenco
        {
            get
            {
                global::System.Nullable<int> value = _lnenco;
                OnGetlnenco(ref value);
                return value;
            }
            set
            {
                if (_lnenco != value)
                {
                  OnlnencoChanging(ref value);
                  ReportPropertyChanging("lnenco");
                  _lnenco = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("lnenco");
                  OnlnencoChanged();
              }
            }
        }
        private global::System.Nullable<int> _lnenco;
        partial void OnGetlnenco(ref global::System.Nullable<int> value);
        partial void OnlnencoChanging(ref global::System.Nullable<int> value);
        partial void OnlnencoChanged();
    
        /// <summary>
        /// There are no comments for operacao in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public string operacao
        {
            get
            {
                string value = _operacao;
                OnGetoperacao(ref value);
                return value;
            }
            set
            {
                if (_operacao != value)
                {
                  OnoperacaoChanging(ref value);
                  ReportPropertyChanging("operacao");
                  _operacao = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("operacao");
                  OnoperacaoChanged();
              }
            }
        }
        private string _operacao;
        partial void OnGetoperacao(ref string value);
        partial void OnoperacaoChanging(ref string value);
        partial void OnoperacaoChanged();
    
        /// <summary>
        /// There are no comments for arm in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string arm
        {
            get
            {
                string value = _arm;
                OnGetarm(ref value);
                return value;
            }
            set
            {
                if (_arm != value)
                {
                  OnarmChanging(ref value);
                  ReportPropertyChanging("arm");
                  _arm = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("arm");
                  OnarmChanged();
              }
            }
        }
        private string _arm;
        partial void OnGetarm(ref string value);
        partial void OnarmChanging(ref string value);
        partial void OnarmChanged();
    
        /// <summary>
        /// There are no comments for artigo in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(12)]
        public string artigo
        {
            get
            {
                string value = _artigo;
                OnGetartigo(ref value);
                return value;
            }
            set
            {
                if (_artigo != value)
                {
                  OnartigoChanging(ref value);
                  ReportPropertyChanging("artigo");
                  _artigo = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("artigo");
                  OnartigoChanged();
              }
            }
        }
        private string _artigo;
        partial void OnGetartigo(ref string value);
        partial void OnartigoChanging(ref string value);
        partial void OnartigoChanged();
    
        /// <summary>
        /// There are no comments for cartaz in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(5)]
        public string cartaz
        {
            get
            {
                string value = _cartaz;
                OnGetcartaz(ref value);
                return value;
            }
            set
            {
                if (_cartaz != value)
                {
                  OncartazChanging(ref value);
                  ReportPropertyChanging("cartaz");
                  _cartaz = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("cartaz");
                  OncartazChanged();
              }
            }
        }
        private string _cartaz;
        partial void OnGetcartaz(ref string value);
        partial void OncartazChanging(ref string value);
        partial void OncartazChanged();
    
        /// <summary>
        /// There are no comments for codcor in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string codcor
        {
            get
            {
                string value = _codcor;
                OnGetcodcor(ref value);
                return value;
            }
            set
            {
                if (_codcor != value)
                {
                  OncodcorChanging(ref value);
                  ReportPropertyChanging("codcor");
                  _codcor = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("codcor");
                  OncodcorChanged();
              }
            }
        }
        private string _codcor;
        partial void OnGetcodcor(ref string value);
        partial void OncodcorChanging(ref string value);
        partial void OncodcorChanged();
    
        /// <summary>
        /// There are no comments for tam in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public string tam
        {
            get
            {
                string value = _tam;
                OnGettam(ref value);
                return value;
            }
            set
            {
                if (_tam != value)
                {
                  OntamChanging(ref value);
                  ReportPropertyChanging("tam");
                  _tam = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("tam");
                  OntamChanged();
              }
            }
        }
        private string _tam;
        partial void OnGettam(ref string value);
        partial void OntamChanging(ref string value);
        partial void OntamChanged();
    
        /// <summary>
        /// There are no comments for situacao in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string situacao
        {
            get
            {
                string value = _situacao;
                OnGetsituacao(ref value);
                return value;
            }
            set
            {
                if (_situacao != value)
                {
                  OnsituacaoChanging(ref value);
                  ReportPropertyChanging("situacao");
                  _situacao = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("situacao");
                  OnsituacaoChanged();
              }
            }
        }
        private string _situacao;
        partial void OnGetsituacao(ref string value);
        partial void OnsituacaoChanging(ref string value);
        partial void OnsituacaoChanged();
    
        /// <summary>
        /// There are no comments for qt in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> qt
        {
            get
            {
                global::System.Nullable<int> value = _qt;
                OnGetqt(ref value);
                return value;
            }
            set
            {
                if (_qt != value)
                {
                  OnqtChanging(ref value);
                  ReportPropertyChanging("qt");
                  _qt = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("qt");
                  OnqtChanged();
              }
            }
        }
        private global::System.Nullable<int> _qt;
        partial void OnGetqt(ref global::System.Nullable<int> value);
        partial void OnqtChanging(ref global::System.Nullable<int> value);
        partial void OnqtChanged();
    
        /// <summary>
        /// There are no comments for data_ini in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> data_ini
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _data_ini;
                OnGetdata_ini(ref value);
                return value;
            }
            set
            {
                if (_data_ini != value)
                {
                  Ondata_iniChanging(ref value);
                  ReportPropertyChanging("data_ini");
                  _data_ini = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("data_ini");
                  Ondata_iniChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _data_ini;
        partial void OnGetdata_ini(ref global::System.Nullable<System.DateTime> value);
        partial void Ondata_iniChanging(ref global::System.Nullable<System.DateTime> value);
        partial void Ondata_iniChanged();
    
        /// <summary>
        /// There are no comments for data_fim in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> data_fim
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _data_fim;
                OnGetdata_fim(ref value);
                return value;
            }
            set
            {
                if (_data_fim != value)
                {
                  Ondata_fimChanging(ref value);
                  ReportPropertyChanging("data_fim");
                  _data_fim = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("data_fim");
                  Ondata_fimChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _data_fim;
        partial void OnGetdata_fim(ref global::System.Nullable<System.DateTime> value);
        partial void Ondata_fimChanging(ref global::System.Nullable<System.DateTime> value);
        partial void Ondata_fimChanged();
    
        /// <summary>
        /// There are no comments for data_ini_vis in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> data_ini_vis
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _data_ini_vis;
                OnGetdata_ini_vis(ref value);
                return value;
            }
            set
            {
                if (_data_ini_vis != value)
                {
                  Ondata_ini_visChanging(ref value);
                  ReportPropertyChanging("data_ini_vis");
                  _data_ini_vis = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("data_ini_vis");
                  Ondata_ini_visChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _data_ini_vis;
        partial void OnGetdata_ini_vis(ref global::System.Nullable<System.DateTime> value);
        partial void Ondata_ini_visChanging(ref global::System.Nullable<System.DateTime> value);
        partial void Ondata_ini_visChanged();
    
        /// <summary>
        /// There are no comments for data_fim_vis in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> data_fim_vis
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _data_fim_vis;
                OnGetdata_fim_vis(ref value);
                return value;
            }
            set
            {
                if (_data_fim_vis != value)
                {
                  Ondata_fim_visChanging(ref value);
                  ReportPropertyChanging("data_fim_vis");
                  _data_fim_vis = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("data_fim_vis");
                  Ondata_fim_visChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _data_fim_vis;
        partial void OnGetdata_fim_vis(ref global::System.Nullable<System.DateTime> value);
        partial void Ondata_fim_visChanging(ref global::System.Nullable<System.DateTime> value);
        partial void Ondata_fim_visChanged();
    
        /// <summary>
        /// There are no comments for seccao in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(6)]
        public string seccao
        {
            get
            {
                string value = _seccao;
                OnGetseccao(ref value);
                return value;
            }
            set
            {
                if (_seccao != value)
                {
                  OnseccaoChanging(ref value);
                  ReportPropertyChanging("seccao");
                  _seccao = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("seccao");
                  OnseccaoChanged();
              }
            }
        }
        private string _seccao;
        partial void OnGetseccao(ref string value);
        partial void OnseccaoChanging(ref string value);
        partial void OnseccaoChanged();
    
        /// <summary>
        /// There are no comments for stat in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public string stat
        {
            get
            {
                string value = _stat;
                OnGetstat(ref value);
                return value;
            }
            set
            {
                if (_stat != value)
                {
                  OnstatChanging(ref value);
                  ReportPropertyChanging("stat");
                  _stat = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("stat");
                  OnstatChanged();
              }
            }
        }
        private string _stat;
        partial void OnGetstat(ref string value);
        partial void OnstatChanging(ref string value);
        partial void OnstatChanged();
    
        /// <summary>
        /// There are no comments for seq in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> seq
        {
            get
            {
                global::System.Nullable<int> value = _seq;
                OnGetseq(ref value);
                return value;
            }
            set
            {
                if (_seq != value)
                {
                  OnseqChanging(ref value);
                  ReportPropertyChanging("seq");
                  _seq = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("seq");
                  OnseqChanged();
              }
            }
        }
        private global::System.Nullable<int> _seq;
        partial void OnGetseq(ref global::System.Nullable<int> value);
        partial void OnseqChanging(ref global::System.Nullable<int> value);
        partial void OnseqChanged();
    
        /// <summary>
        /// There are no comments for tempo in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> tempo
        {
            get
            {
                global::System.Nullable<decimal> value = _tempo;
                OnGettempo(ref value);
                return value;
            }
            set
            {
                if (_tempo != value)
                {
                  OntempoChanging(ref value);
                  ReportPropertyChanging("tempo");
                  _tempo = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("tempo");
                  OntempoChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _tempo;
        partial void OnGettempo(ref global::System.Nullable<decimal> value);
        partial void OntempoChanging(ref global::System.Nullable<decimal> value);
        partial void OntempoChanged();
    
        /// <summary>
        /// There are no comments for tempo_op_un in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> tempo_op_un
        {
            get
            {
                global::System.Nullable<decimal> value = _tempo_op_un;
                OnGettempo_op_un(ref value);
                return value;
            }
            set
            {
                if (_tempo_op_un != value)
                {
                  Ontempo_op_unChanging(ref value);
                  ReportPropertyChanging("tempo_op_un");
                  _tempo_op_un = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("tempo_op_un");
                  Ontempo_op_unChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _tempo_op_un;
        partial void OnGettempo_op_un(ref global::System.Nullable<decimal> value);
        partial void Ontempo_op_unChanging(ref global::System.Nullable<decimal> value);
        partial void Ontempo_op_unChanged();
    
        /// <summary>
        /// There are no comments for planeada in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(1)]
        public string planeada
        {
            get
            {
                string value = _planeada;
                OnGetplaneada(ref value);
                return value;
            }
            set
            {
                if (_planeada != value)
                {
                  OnplaneadaChanging(ref value);
                  ReportPropertyChanging("planeada");
                  _planeada = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("planeada");
                  OnplaneadaChanged();
              }
            }
        }
        private string _planeada = @"V";
        partial void OnGetplaneada(ref string value);
        partial void OnplaneadaChanging(ref string value);
        partial void OnplaneadaChanged();
    
        /// <summary>
        /// There are no comments for selected in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<bool> selected
        {
            get
            {
                global::System.Nullable<bool> value = _selected;
                OnGetselected(ref value);
                return value;
            }
            set
            {
                if (_selected != value)
                {
                  OnselectedChanging(ref value);
                  ReportPropertyChanging("selected");
                  _selected = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("selected");
                  OnselectedChanged();
              }
            }
        }
        private global::System.Nullable<bool> _selected;
        partial void OnGetselected(ref global::System.Nullable<bool> value);
        partial void OnselectedChanging(ref global::System.Nullable<bool> value);
        partial void OnselectedChanged();
    
        /// <summary>
        /// There are no comments for start in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> start
        {
            get
            {
                global::System.Nullable<decimal> value = _start;
                OnGetstart(ref value);
                return value;
            }
            set
            {
                if (_start != value)
                {
                  OnstartChanging(ref value);
                  ReportPropertyChanging("start");
                  _start = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("start");
                  OnstartChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _start;
        partial void OnGetstart(ref global::System.Nullable<decimal> value);
        partial void OnstartChanging(ref global::System.Nullable<decimal> value);
        partial void OnstartChanged();
    
        /// <summary>
        /// There are no comments for finish in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> finish
        {
            get
            {
                global::System.Nullable<decimal> value = _finish;
                OnGetfinish(ref value);
                return value;
            }
            set
            {
                if (_finish != value)
                {
                  OnfinishChanging(ref value);
                  ReportPropertyChanging("finish");
                  _finish = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("finish");
                  OnfinishChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _finish;
        partial void OnGetfinish(ref global::System.Nullable<decimal> value);
        partial void OnfinishChanging(ref global::System.Nullable<decimal> value);
        partial void OnfinishChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            mrp_oper obj = new mrp_oper();
            obj.Order_Id = Order_Id;
            obj.Department_id = Department_id;
            obj.Department = Department;
            obj.Release_min = Release_min;
            obj.Release_mostlikely = Release_mostlikely;
            obj.Release_max = Release_max;
            obj.Release_data = Release_data;
            obj.Process_min = Process_min;
            obj.Process_mostlikely = Process_mostlikely;
            obj.Process_max = Process_max;
            obj.tipo = tipo;
            obj.nrenco = nrenco;
            obj.lnenco = lnenco;
            obj.operacao = operacao;
            obj.arm = arm;
            obj.artigo = artigo;
            obj.cartaz = cartaz;
            obj.codcor = codcor;
            obj.tam = tam;
            obj.situacao = situacao;
            obj.qt = qt;
            obj.data_ini = data_ini;
            obj.data_fim = data_fim;
            obj.data_ini_vis = data_ini_vis;
            obj.data_fim_vis = data_fim_vis;
            obj.seccao = seccao;
            obj.stat = stat;
            obj.seq = seq;
            obj.tempo = tempo;
            obj.tempo_op_un = tempo_op_un;
            obj.planeada = planeada;
            obj.selected = selected;
            obj.start = start;
            obj.finish = finish;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          mrp_oper toCompare = obj as mrp_oper;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Order_Id, toCompare.Order_Id))
            return false;
          if (!Object.Equals(this.Department_id, toCompare.Department_id))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Order_Id.GetHashCode();
          hashCode = (hashCode * 7) + Department_id.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
