//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.horarios in the schema.
    /// </summary>
    /// <KeyProperties>
    /// cod_horario
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="horarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class horarios : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new horarios object.
        /// </summary>
        /// <param name="cod_horario">Initial value of cod_horario.</param>
        public static horarios Createhorarios(string cod_horario)
        {
            horarios horarios = new horarios();
            horarios.cod_horario = cod_horario;
            return horarios;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for cod_horario in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string cod_horario
        {
            get
            {
                string value = _cod_horario;
                OnGetcod_horario(ref value);
                return value;
            }
            set
            {
                if (_cod_horario != value)
                {
                  Oncod_horarioChanging(ref value);
                  ReportPropertyChanging("cod_horario");
                  _cod_horario = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("cod_horario");
                  Oncod_horarioChanged();
              }
            }
        }
        private string _cod_horario;
        partial void OnGetcod_horario(ref string value);
        partial void Oncod_horarioChanging(ref string value);
        partial void Oncod_horarioChanged();
    
        /// <summary>
        /// There are no comments for dom in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> dom
        {
            get
            {
                global::System.Nullable<int> value = _dom;
                OnGetdom(ref value);
                return value;
            }
            set
            {
                if (_dom != value)
                {
                  OndomChanging(ref value);
                  ReportPropertyChanging("dom");
                  _dom = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("dom");
                  OndomChanged();
              }
            }
        }
        private global::System.Nullable<int> _dom;
        partial void OnGetdom(ref global::System.Nullable<int> value);
        partial void OndomChanging(ref global::System.Nullable<int> value);
        partial void OndomChanged();
    
        /// <summary>
        /// There are no comments for seg in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> seg
        {
            get
            {
                global::System.Nullable<int> value = _seg;
                OnGetseg(ref value);
                return value;
            }
            set
            {
                if (_seg != value)
                {
                  OnsegChanging(ref value);
                  ReportPropertyChanging("seg");
                  _seg = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("seg");
                  OnsegChanged();
              }
            }
        }
        private global::System.Nullable<int> _seg;
        partial void OnGetseg(ref global::System.Nullable<int> value);
        partial void OnsegChanging(ref global::System.Nullable<int> value);
        partial void OnsegChanged();
    
        /// <summary>
        /// There are no comments for ter in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> ter
        {
            get
            {
                global::System.Nullable<int> value = _ter;
                OnGetter(ref value);
                return value;
            }
            set
            {
                if (_ter != value)
                {
                  OnterChanging(ref value);
                  ReportPropertyChanging("ter");
                  _ter = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("ter");
                  OnterChanged();
              }
            }
        }
        private global::System.Nullable<int> _ter;
        partial void OnGetter(ref global::System.Nullable<int> value);
        partial void OnterChanging(ref global::System.Nullable<int> value);
        partial void OnterChanged();
    
        /// <summary>
        /// There are no comments for qua in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> qua
        {
            get
            {
                global::System.Nullable<int> value = _qua;
                OnGetqua(ref value);
                return value;
            }
            set
            {
                if (_qua != value)
                {
                  OnquaChanging(ref value);
                  ReportPropertyChanging("qua");
                  _qua = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("qua");
                  OnquaChanged();
              }
            }
        }
        private global::System.Nullable<int> _qua;
        partial void OnGetqua(ref global::System.Nullable<int> value);
        partial void OnquaChanging(ref global::System.Nullable<int> value);
        partial void OnquaChanged();
    
        /// <summary>
        /// There are no comments for qui in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> qui
        {
            get
            {
                global::System.Nullable<int> value = _qui;
                OnGetqui(ref value);
                return value;
            }
            set
            {
                if (_qui != value)
                {
                  OnquiChanging(ref value);
                  ReportPropertyChanging("qui");
                  _qui = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("qui");
                  OnquiChanged();
              }
            }
        }
        private global::System.Nullable<int> _qui;
        partial void OnGetqui(ref global::System.Nullable<int> value);
        partial void OnquiChanging(ref global::System.Nullable<int> value);
        partial void OnquiChanged();
    
        /// <summary>
        /// There are no comments for sex in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> sex
        {
            get
            {
                global::System.Nullable<int> value = _sex;
                OnGetsex(ref value);
                return value;
            }
            set
            {
                if (_sex != value)
                {
                  OnsexChanging(ref value);
                  ReportPropertyChanging("sex");
                  _sex = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("sex");
                  OnsexChanged();
              }
            }
        }
        private global::System.Nullable<int> _sex;
        partial void OnGetsex(ref global::System.Nullable<int> value);
        partial void OnsexChanging(ref global::System.Nullable<int> value);
        partial void OnsexChanged();
    
        /// <summary>
        /// There are no comments for sab in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> sab
        {
            get
            {
                global::System.Nullable<int> value = _sab;
                OnGetsab(ref value);
                return value;
            }
            set
            {
                if (_sab != value)
                {
                  OnsabChanging(ref value);
                  ReportPropertyChanging("sab");
                  _sab = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("sab");
                  OnsabChanged();
              }
            }
        }
        private global::System.Nullable<int> _sab;
        partial void OnGetsab(ref global::System.Nullable<int> value);
        partial void OnsabChanging(ref global::System.Nullable<int> value);
        partial void OnsabChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            horarios obj = new horarios();
            obj.cod_horario = cod_horario;
            obj.dom = dom;
            obj.seg = seg;
            obj.ter = ter;
            obj.qua = qua;
            obj.qui = qui;
            obj.sex = sex;
            obj.sab = sab;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          horarios toCompare = obj as horarios;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.cod_horario, toCompare.cod_horario))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + cod_horario.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
