//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.PARAM_WEB in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IDParam
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="PARAM_WEB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PARAM_WEB : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new PARAM_WEB object.
        /// </summary>
        /// <param name="iDParam">Initial value of IDParam.</param>
        /// <param name="param">Initial value of Param.</param>
        public static PARAM_WEB CreatePARAM_WEB(string iDParam, string param)
        {
            PARAM_WEB pARAM_WEB = new PARAM_WEB();
            pARAM_WEB.IDParam = iDParam;
            pARAM_WEB.Param = param;
            return pARAM_WEB;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for IDParam in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(40)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string IDParam
        {
            get
            {
                string value = _IDParam;
                OnGetIDParam(ref value);
                return value;
            }
            set
            {
                if (_IDParam != value)
                {
                  OnIDParamChanging(ref value);
                  ReportPropertyChanging("IDParam");
                  _IDParam = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("IDParam");
                  OnIDParamChanged();
              }
            }
        }
        private string _IDParam = @"";
        partial void OnGetIDParam(ref string value);
        partial void OnIDParamChanging(ref string value);
        partial void OnIDParamChanged();
    
        /// <summary>
        /// There are no comments for DescParam in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(150)]
        public string DescParam
        {
            get
            {
                string value = _DescParam;
                OnGetDescParam(ref value);
                return value;
            }
            set
            {
                if (_DescParam != value)
                {
                  OnDescParamChanging(ref value);
                  ReportPropertyChanging("DescParam");
                  _DescParam = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DescParam");
                  OnDescParamChanged();
              }
            }
        }
        private string _DescParam = @"";
        partial void OnGetDescParam(ref string value);
        partial void OnDescParamChanging(ref string value);
        partial void OnDescParamChanged();
    
        /// <summary>
        /// There are no comments for Param in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(300)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string Param
        {
            get
            {
                string value = _Param;
                OnGetParam(ref value);
                return value;
            }
            set
            {
                if (_Param != value)
                {
                  OnParamChanging(ref value);
                  ReportPropertyChanging("Param");
                  _Param = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("Param");
                  OnParamChanged();
              }
            }
        }
        private string _Param = @"";
        partial void OnGetParam(ref string value);
        partial void OnParamChanging(ref string value);
        partial void OnParamChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            PARAM_WEB obj = new PARAM_WEB();
            obj.IDParam = IDParam;
            obj.DescParam = DescParam;
            obj.Param = Param;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          PARAM_WEB toCompare = obj as PARAM_WEB;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IDParam, toCompare.IDParam))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IDParam.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
