//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.TAB_CONSERTOS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CodConserto
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="TAB_CONSERTOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAB_CONSERTOS : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new TAB_CONSERTOS object.
        /// </summary>
        /// <param name="codConserto">Initial value of CodConserto.</param>
        public static TAB_CONSERTOS CreateTAB_CONSERTOS(int codConserto)
        {
            TAB_CONSERTOS tAB_CONSERTOS = new TAB_CONSERTOS();
            tAB_CONSERTOS.CodConserto = codConserto;
            return tAB_CONSERTOS;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for CodConserto in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public int CodConserto
        {
            get
            {
                int value = _CodConserto;
                OnGetCodConserto(ref value);
                return value;
            }
            set
            {
                if (_CodConserto != value)
                {
                  OnCodConsertoChanging(ref value);
                  ReportPropertyChanging("CodConserto");
                  _CodConserto = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("CodConserto");
                  OnCodConsertoChanged();
              }
            }
        }
        private int _CodConserto;
        partial void OnGetCodConserto(ref int value);
        partial void OnCodConsertoChanging(ref int value);
        partial void OnCodConsertoChanged();
    
        /// <summary>
        /// There are no comments for Descricao in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                string value = _Descricao;
                OnGetDescricao(ref value);
                return value;
            }
            set
            {
                if (_Descricao != value)
                {
                  OnDescricaoChanging(ref value);
                  ReportPropertyChanging("Descricao");
                  _Descricao = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Descricao");
                  OnDescricaoChanged();
              }
            }
        }
        private string _Descricao;
        partial void OnGetDescricao(ref string value);
        partial void OnDescricaoChanging(ref string value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// There are no comments for Preco in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<decimal> Preco
        {
            get
            {
                global::System.Nullable<decimal> value = _Preco;
                OnGetPreco(ref value);
                return value;
            }
            set
            {
                if (_Preco != value)
                {
                  OnPrecoChanging(ref value);
                  ReportPropertyChanging("Preco");
                  _Preco = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Preco");
                  OnPrecoChanged();
              }
            }
        }
        private global::System.Nullable<decimal> _Preco;
        partial void OnGetPreco(ref global::System.Nullable<decimal> value);
        partial void OnPrecoChanging(ref global::System.Nullable<decimal> value);
        partial void OnPrecoChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            TAB_CONSERTOS obj = new TAB_CONSERTOS();
            obj.CodConserto = CodConserto;
            obj.Descricao = Descricao;
            obj.Preco = Preco;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          TAB_CONSERTOS toCompare = obj as TAB_CONSERTOS;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.CodConserto, toCompare.CodConserto))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + CodConserto.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
