//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.CAIXA_MODOPAG in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MODOPAG
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="CAIXA_MODOPAG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CAIXA_MODOPAG : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new CAIXA_MODOPAG object.
        /// </summary>
        /// <param name="mODOPAG">Initial value of MODOPAG.</param>
        public static CAIXA_MODOPAG CreateCAIXA_MODOPAG(string mODOPAG)
        {
            CAIXA_MODOPAG cAIXA_MODOPAG = new CAIXA_MODOPAG();
            cAIXA_MODOPAG.MODOPAG = mODOPAG;
            return cAIXA_MODOPAG;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for MODOPAG in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string MODOPAG
        {
            get
            {
                string value = _MODOPAG;
                OnGetMODOPAG(ref value);
                return value;
            }
            set
            {
                if (_MODOPAG != value)
                {
                  OnMODOPAGChanging(ref value);
                  ReportPropertyChanging("MODOPAG");
                  _MODOPAG = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("MODOPAG");
                  OnMODOPAGChanged();
              }
            }
        }
        private string _MODOPAG;
        partial void OnGetMODOPAG(ref string value);
        partial void OnMODOPAGChanging(ref string value);
        partial void OnMODOPAGChanged();
    
        /// <summary>
        /// There are no comments for DESCRICAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string DESCRICAO
        {
            get
            {
                string value = _DESCRICAO;
                OnGetDESCRICAO(ref value);
                return value;
            }
            set
            {
                if (_DESCRICAO != value)
                {
                  OnDESCRICAOChanging(ref value);
                  ReportPropertyChanging("DESCRICAO");
                  _DESCRICAO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DESCRICAO");
                  OnDESCRICAOChanged();
              }
            }
        }
        private string _DESCRICAO;
        partial void OnGetDESCRICAO(ref string value);
        partial void OnDESCRICAOChanging(ref string value);
        partial void OnDESCRICAOChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            CAIXA_MODOPAG obj = new CAIXA_MODOPAG();
            obj.MODOPAG = MODOPAG;
            obj.DESCRICAO = DESCRICAO;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          CAIXA_MODOPAG toCompare = obj as CAIXA_MODOPAG;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.MODOPAG, toCompare.MODOPAG))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + MODOPAG.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
