//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.mensagensMostrador in the schema.
    /// </summary>
    /// <KeyProperties>
    /// idMsg
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="mensagensMostrador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mensagensMostrador : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new mensagensMostrador object.
        /// </summary>
        /// <param name="idMsg">Initial value of idMsg.</param>
        /// <param name="dataInicio">Initial value of dataInicio.</param>
        /// <param name="dataFim">Initial value of dataFim.</param>
        /// <param name="mensagem">Initial value of mensagem.</param>
        /// <param name="mostrada">Initial value of mostrada.</param>
        public static mensagensMostrador CreatemensagensMostrador(global::System.Guid idMsg, global::System.DateTime dataInicio, global::System.DateTime dataFim, string mensagem, bool mostrada)
        {
            mensagensMostrador mensagensMostrador = new mensagensMostrador();
            mensagensMostrador.idMsg = idMsg;
            mensagensMostrador.dataInicio = dataInicio;
            mensagensMostrador.dataFim = dataFim;
            mensagensMostrador.mensagem = mensagem;
            mensagensMostrador.mostrada = mostrada;
            return mensagensMostrador;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for idMsg in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public global::System.Guid idMsg
        {
            get
            {
                global::System.Guid value = _idMsg;
                OnGetidMsg(ref value);
                return value;
            }
            set
            {
                if (_idMsg != value)
                {
                  OnidMsgChanging(ref value);
                  ReportPropertyChanging("idMsg");
                  _idMsg = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("idMsg");
                  OnidMsgChanged();
              }
            }
        }
        private global::System.Guid _idMsg;
        partial void OnGetidMsg(ref global::System.Guid value);
        partial void OnidMsgChanging(ref global::System.Guid value);
        partial void OnidMsgChanged();
    
        /// <summary>
        /// There are no comments for dataInicio in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Required()]
        public global::System.DateTime dataInicio
        {
            get
            {
                global::System.DateTime value = _dataInicio;
                OnGetdataInicio(ref value);
                return value;
            }
            set
            {
                if (_dataInicio != value)
                {
                  OndataInicioChanging(ref value);
                  ReportPropertyChanging("dataInicio");
                  _dataInicio = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("dataInicio");
                  OndataInicioChanged();
              }
            }
        }
        private global::System.DateTime _dataInicio;
        partial void OnGetdataInicio(ref global::System.DateTime value);
        partial void OndataInicioChanging(ref global::System.DateTime value);
        partial void OndataInicioChanged();
    
        /// <summary>
        /// There are no comments for dataFim in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Required()]
        public global::System.DateTime dataFim
        {
            get
            {
                global::System.DateTime value = _dataFim;
                OnGetdataFim(ref value);
                return value;
            }
            set
            {
                if (_dataFim != value)
                {
                  OndataFimChanging(ref value);
                  ReportPropertyChanging("dataFim");
                  _dataFim = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("dataFim");
                  OndataFimChanged();
              }
            }
        }
        private global::System.DateTime _dataFim;
        partial void OnGetdataFim(ref global::System.DateTime value);
        partial void OndataFimChanging(ref global::System.DateTime value);
        partial void OndataFimChanged();
    
        /// <summary>
        /// There are no comments for mensagem in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Required()]
        public string mensagem
        {
            get
            {
                string value = _mensagem;
                OnGetmensagem(ref value);
                return value;
            }
            set
            {
                if (_mensagem != value)
                {
                  OnmensagemChanging(ref value);
                  ReportPropertyChanging("mensagem");
                  _mensagem = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("mensagem");
                  OnmensagemChanged();
              }
            }
        }
        private string _mensagem;
        partial void OnGetmensagem(ref string value);
        partial void OnmensagemChanging(ref string value);
        partial void OnmensagemChanged();
    
        /// <summary>
        /// There are no comments for mostrada in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Required()]
        public bool mostrada
        {
            get
            {
                bool value = _mostrada;
                OnGetmostrada(ref value);
                return value;
            }
            set
            {
                if (_mostrada != value)
                {
                  OnmostradaChanging(ref value);
                  ReportPropertyChanging("mostrada");
                  _mostrada = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("mostrada");
                  OnmostradaChanged();
              }
            }
        }
        private bool _mostrada;
        partial void OnGetmostrada(ref bool value);
        partial void OnmostradaChanging(ref bool value);
        partial void OnmostradaChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            mensagensMostrador obj = new mensagensMostrador();
            obj.idMsg = idMsg;
            obj.dataInicio = dataInicio;
            obj.dataFim = dataFim;
            obj.mensagem = mensagem;
            obj.mostrada = mostrada;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          mensagensMostrador toCompare = obj as mensagensMostrador;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.idMsg, toCompare.idMsg))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + idMsg.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
