//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.PPS3_KPI_DESCRICAO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// COD_KPI
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="PPS3_KPI_DESCRICAO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PPS3_KPI_DESCRICAO : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new PPS3_KPI_DESCRICAO object.
        /// </summary>
        /// <param name="cOD_KPI">Initial value of COD_KPI.</param>
        public static PPS3_KPI_DESCRICAO CreatePPS3_KPI_DESCRICAO(string cOD_KPI)
        {
            PPS3_KPI_DESCRICAO pPS3_KPI_DESCRICAO = new PPS3_KPI_DESCRICAO();
            pPS3_KPI_DESCRICAO.COD_KPI = cOD_KPI;
            return pPS3_KPI_DESCRICAO;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for COD_KPI in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(5)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string COD_KPI
        {
            get
            {
                string value = _COD_KPI;
                OnGetCOD_KPI(ref value);
                return value;
            }
            set
            {
                if (_COD_KPI != value)
                {
                  OnCOD_KPIChanging(ref value);
                  ReportPropertyChanging("COD_KPI");
                  _COD_KPI = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("COD_KPI");
                  OnCOD_KPIChanged();
              }
            }
        }
        private string _COD_KPI;
        partial void OnGetCOD_KPI(ref string value);
        partial void OnCOD_KPIChanging(ref string value);
        partial void OnCOD_KPIChanged();
    
        /// <summary>
        /// There are no comments for DESCRIPTION in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string DESCRIPTION
        {
            get
            {
                string value = _DESCRIPTION;
                OnGetDESCRIPTION(ref value);
                return value;
            }
            set
            {
                if (_DESCRIPTION != value)
                {
                  OnDESCRIPTIONChanging(ref value);
                  ReportPropertyChanging("DESCRIPTION");
                  _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DESCRIPTION");
                  OnDESCRIPTIONChanged();
              }
            }
        }
        private string _DESCRIPTION;
        partial void OnGetDESCRIPTION(ref string value);
        partial void OnDESCRIPTIONChanging(ref string value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// There are no comments for SELECCAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<bool> SELECCAO
        {
            get
            {
                global::System.Nullable<bool> value = _SELECCAO;
                OnGetSELECCAO(ref value);
                return value;
            }
            set
            {
                if (_SELECCAO != value)
                {
                  OnSELECCAOChanging(ref value);
                  ReportPropertyChanging("SELECCAO");
                  _SELECCAO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("SELECCAO");
                  OnSELECCAOChanged();
              }
            }
        }
        private global::System.Nullable<bool> _SELECCAO;
        partial void OnGetSELECCAO(ref global::System.Nullable<bool> value);
        partial void OnSELECCAOChanging(ref global::System.Nullable<bool> value);
        partial void OnSELECCAOChanged();
    
        /// <summary>
        /// There are no comments for DESC_ABRV in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(12)]
        public string DESC_ABRV
        {
            get
            {
                string value = _DESC_ABRV;
                OnGetDESC_ABRV(ref value);
                return value;
            }
            set
            {
                if (_DESC_ABRV != value)
                {
                  OnDESC_ABRVChanging(ref value);
                  ReportPropertyChanging("DESC_ABRV");
                  _DESC_ABRV = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DESC_ABRV");
                  OnDESC_ABRVChanged();
              }
            }
        }
        private string _DESC_ABRV;
        partial void OnGetDESC_ABRV(ref string value);
        partial void OnDESC_ABRVChanging(ref string value);
        partial void OnDESC_ABRVChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            PPS3_KPI_DESCRICAO obj = new PPS3_KPI_DESCRICAO();
            obj.COD_KPI = COD_KPI;
            obj.DESCRIPTION = DESCRIPTION;
            obj.SELECCAO = SELECCAO;
            obj.DESC_ABRV = DESC_ABRV;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          PPS3_KPI_DESCRICAO toCompare = obj as PPS3_KPI_DESCRICAO;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.COD_KPI, toCompare.COD_KPI))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + COD_KPI.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
