//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.TS_CLIENTES in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="TS_CLIENTES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TS_CLIENTES : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new TS_CLIENTES object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        public static TS_CLIENTES CreateTS_CLIENTES(global::System.Guid id)
        {
            TS_CLIENTES tS_CLIENTES = new TS_CLIENTES();
            tS_CLIENTES.id = id;
            return tS_CLIENTES;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for id in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public global::System.Guid id
        {
            get
            {
                global::System.Guid value = _id;
                OnGetid(ref value);
                return value;
            }
            set
            {
                if (_id != value)
                {
                  OnidChanging(ref value);
                  ReportPropertyChanging("id");
                  _id = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("id");
                  OnidChanged();
              }
            }
        }
        private global::System.Guid _id;
        partial void OnGetid(ref global::System.Guid value);
        partial void OnidChanging(ref global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// There are no comments for idCliente in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> idCliente
        {
            get
            {
                global::System.Nullable<int> value = _idCliente;
                OnGetidCliente(ref value);
                return value;
            }
            set
            {
                if (_idCliente != value)
                {
                  OnidClienteChanging(ref value);
                  ReportPropertyChanging("idCliente");
                  _idCliente = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("idCliente");
                  OnidClienteChanged();
              }
            }
        }
        private global::System.Nullable<int> _idCliente;
        partial void OnGetidCliente(ref global::System.Nullable<int> value);
        partial void OnidClienteChanging(ref global::System.Nullable<int> value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// There are no comments for nome in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string nome
        {
            get
            {
                string value = _nome;
                OnGetnome(ref value);
                return value;
            }
            set
            {
                if (_nome != value)
                {
                  OnnomeChanging(ref value);
                  ReportPropertyChanging("nome");
                  _nome = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("nome");
                  OnnomeChanged();
              }
            }
        }
        private string _nome;
        partial void OnGetnome(ref string value);
        partial void OnnomeChanging(ref string value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// There are no comments for altura in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<double> altura
        {
            get
            {
                global::System.Nullable<double> value = _altura;
                OnGetaltura(ref value);
                return value;
            }
            set
            {
                if (_altura != value)
                {
                  OnalturaChanging(ref value);
                  ReportPropertyChanging("altura");
                  _altura = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("altura");
                  OnalturaChanged();
              }
            }
        }
        private global::System.Nullable<double> _altura;
        partial void OnGetaltura(ref global::System.Nullable<double> value);
        partial void OnalturaChanging(ref global::System.Nullable<double> value);
        partial void OnalturaChanged();
    
        /// <summary>
        /// There are no comments for dataNasc in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> dataNasc
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _dataNasc;
                OnGetdataNasc(ref value);
                return value;
            }
            set
            {
                if (_dataNasc != value)
                {
                  OndataNascChanging(ref value);
                  ReportPropertyChanging("dataNasc");
                  _dataNasc = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("dataNasc");
                  OndataNascChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _dataNasc;
        partial void OnGetdataNasc(ref global::System.Nullable<System.DateTime> value);
        partial void OndataNascChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OndataNascChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            TS_CLIENTES obj = new TS_CLIENTES();
            obj.id = id;
            obj.idCliente = idCliente;
            obj.nome = nome;
            obj.altura = altura;
            obj.dataNasc = dataNasc;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          TS_CLIENTES toCompare = obj as TS_CLIENTES;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.id, toCompare.id))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + id.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
