//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.TAB_HORARIOS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ARM
    /// DATA
    /// CODFUNC
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="TAB_HORARIOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAB_HORARIOS : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new TAB_HORARIOS object.
        /// </summary>
        /// <param name="aRM">Initial value of ARM.</param>
        /// <param name="dATA">Initial value of DATA.</param>
        /// <param name="cODFUNC">Initial value of CODFUNC.</param>
        /// <param name="cOD_TURNO">Initial value of COD_TURNO.</param>
        public static TAB_HORARIOS CreateTAB_HORARIOS(string aRM, global::System.DateTime dATA, string cODFUNC, string cOD_TURNO)
        {
            TAB_HORARIOS tAB_HORARIOS = new TAB_HORARIOS();
            tAB_HORARIOS.ARM = aRM;
            tAB_HORARIOS.DATA = dATA;
            tAB_HORARIOS.CODFUNC = cODFUNC;
            tAB_HORARIOS.COD_TURNO = cOD_TURNO;
            return tAB_HORARIOS;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for ARM in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string ARM
        {
            get
            {
                string value = _ARM;
                OnGetARM(ref value);
                return value;
            }
            set
            {
                if (_ARM != value)
                {
                  OnARMChanging(ref value);
                  ReportPropertyChanging("ARM");
                  _ARM = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("ARM");
                  OnARMChanged();
              }
            }
        }
        private string _ARM;
        partial void OnGetARM(ref string value);
        partial void OnARMChanging(ref string value);
        partial void OnARMChanged();
    
        /// <summary>
        /// There are no comments for DATA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public global::System.DateTime DATA
        {
            get
            {
                global::System.DateTime value = _DATA;
                OnGetDATA(ref value);
                return value;
            }
            set
            {
                if (_DATA != value)
                {
                  OnDATAChanging(ref value);
                  ReportPropertyChanging("DATA");
                  _DATA = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DATA");
                  OnDATAChanged();
              }
            }
        }
        private global::System.DateTime _DATA;
        partial void OnGetDATA(ref global::System.DateTime value);
        partial void OnDATAChanging(ref global::System.DateTime value);
        partial void OnDATAChanged();
    
        /// <summary>
        /// There are no comments for CODFUNC in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string CODFUNC
        {
            get
            {
                string value = _CODFUNC;
                OnGetCODFUNC(ref value);
                return value;
            }
            set
            {
                if (_CODFUNC != value)
                {
                  OnCODFUNCChanging(ref value);
                  ReportPropertyChanging("CODFUNC");
                  _CODFUNC = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("CODFUNC");
                  OnCODFUNCChanged();
              }
            }
        }
        private string _CODFUNC;
        partial void OnGetCODFUNC(ref string value);
        partial void OnCODFUNCChanging(ref string value);
        partial void OnCODFUNCChanged();
    
        /// <summary>
        /// There are no comments for COD_TURNO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(2)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string COD_TURNO
        {
            get
            {
                string value = _COD_TURNO;
                OnGetCOD_TURNO(ref value);
                return value;
            }
            set
            {
                if (_COD_TURNO != value)
                {
                  OnCOD_TURNOChanging(ref value);
                  ReportPropertyChanging("COD_TURNO");
                  _COD_TURNO = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("COD_TURNO");
                  OnCOD_TURNOChanged();
              }
            }
        }
        private string _COD_TURNO;
        partial void OnGetCOD_TURNO(ref string value);
        partial void OnCOD_TURNOChanging(ref string value);
        partial void OnCOD_TURNOChanged();
    
        /// <summary>
        /// There are no comments for HORA_INI in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> HORA_INI
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _HORA_INI;
                OnGetHORA_INI(ref value);
                return value;
            }
            set
            {
                if (_HORA_INI != value)
                {
                  OnHORA_INIChanging(ref value);
                  ReportPropertyChanging("HORA_INI");
                  _HORA_INI = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("HORA_INI");
                  OnHORA_INIChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _HORA_INI;
        partial void OnGetHORA_INI(ref global::System.Nullable<System.DateTime> value);
        partial void OnHORA_INIChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnHORA_INIChanged();
    
        /// <summary>
        /// There are no comments for HORA_FIM in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<System.DateTime> HORA_FIM
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _HORA_FIM;
                OnGetHORA_FIM(ref value);
                return value;
            }
            set
            {
                if (_HORA_FIM != value)
                {
                  OnHORA_FIMChanging(ref value);
                  ReportPropertyChanging("HORA_FIM");
                  _HORA_FIM = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("HORA_FIM");
                  OnHORA_FIMChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _HORA_FIM;
        partial void OnGetHORA_FIM(ref global::System.Nullable<System.DateTime> value);
        partial void OnHORA_FIMChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnHORA_FIMChanged();
    
        /// <summary>
        /// There are no comments for ANO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> ANO
        {
            get
            {
                global::System.Nullable<int> value = _ANO;
                OnGetANO(ref value);
                return value;
            }
            set
            {
                if (_ANO != value)
                {
                  OnANOChanging(ref value);
                  ReportPropertyChanging("ANO");
                  _ANO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("ANO");
                  OnANOChanged();
              }
            }
        }
        private global::System.Nullable<int> _ANO;
        partial void OnGetANO(ref global::System.Nullable<int> value);
        partial void OnANOChanging(ref global::System.Nullable<int> value);
        partial void OnANOChanged();
    
        /// <summary>
        /// There are no comments for MES in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> MES
        {
            get
            {
                global::System.Nullable<int> value = _MES;
                OnGetMES(ref value);
                return value;
            }
            set
            {
                if (_MES != value)
                {
                  OnMESChanging(ref value);
                  ReportPropertyChanging("MES");
                  _MES = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("MES");
                  OnMESChanged();
              }
            }
        }
        private global::System.Nullable<int> _MES;
        partial void OnGetMES(ref global::System.Nullable<int> value);
        partial void OnMESChanging(ref global::System.Nullable<int> value);
        partial void OnMESChanged();
    
        /// <summary>
        /// There are no comments for DIA in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public global::System.Nullable<int> DIA
        {
            get
            {
                global::System.Nullable<int> value = _DIA;
                OnGetDIA(ref value);
                return value;
            }
            set
            {
                if (_DIA != value)
                {
                  OnDIAChanging(ref value);
                  ReportPropertyChanging("DIA");
                  _DIA = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DIA");
                  OnDIAChanged();
              }
            }
        }
        private global::System.Nullable<int> _DIA;
        partial void OnGetDIA(ref global::System.Nullable<int> value);
        partial void OnDIAChanging(ref global::System.Nullable<int> value);
        partial void OnDIAChanged();
    
        /// <summary>
        /// There are no comments for DESCRICAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.StringLength(20)]
        public string DESCRICAO
        {
            get
            {
                string value = _DESCRICAO;
                OnGetDESCRICAO(ref value);
                return value;
            }
            set
            {
                if (_DESCRICAO != value)
                {
                  OnDESCRICAOChanging(ref value);
                  ReportPropertyChanging("DESCRICAO");
                  _DESCRICAO = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("DESCRICAO");
                  OnDESCRICAOChanged();
              }
            }
        }
        private string _DESCRICAO;
        partial void OnGetDESCRICAO(ref string value);
        partial void OnDESCRICAOChanging(ref string value);
        partial void OnDESCRICAOChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            TAB_HORARIOS obj = new TAB_HORARIOS();
            obj.ARM = ARM;
            obj.DATA = DATA;
            obj.CODFUNC = CODFUNC;
            obj.COD_TURNO = COD_TURNO;
            obj.HORA_INI = HORA_INI;
            obj.HORA_FIM = HORA_FIM;
            obj.ANO = ANO;
            obj.MES = MES;
            obj.DIA = DIA;
            obj.DESCRICAO = DESCRICAO;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          TAB_HORARIOS toCompare = obj as TAB_HORARIOS;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.ARM, toCompare.ARM))
            return false;
          if (!Object.Equals(this.DATA, toCompare.DATA))
            return false;
          if (!Object.Equals(this.CODFUNC, toCompare.CODFUNC))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + ARM.GetHashCode();
          hashCode = (hashCode * 7) + DATA.GetHashCode();
          hashCode = (hashCode * 7) + CODFUNC.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
