//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 08-11-2014 10:46:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace DataGiic_LiagoModel
{

    /// <summary>
    /// There are no comments for DataGiic_LiagoModel.TAB_OBJLOJA in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ARM
    /// ANO
    /// MES
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="DataGiic_LiagoModel", Name="TAB_OBJLOJA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAB_OBJLOJA : EntityObject, ICloneable    {
        #region Factory Method

        /// <summary>
        /// Create a new TAB_OBJLOJA object.
        /// </summary>
        /// <param name="aRM">Initial value of ARM.</param>
        /// <param name="aNO">Initial value of ANO.</param>
        /// <param name="mES">Initial value of MES.</param>
        /// <param name="lIMITE">Initial value of LIMITE.</param>
        /// <param name="cOMISSAO">Initial value of COMISSAO.</param>
        public static TAB_OBJLOJA CreateTAB_OBJLOJA(string aRM, int aNO, short mES, decimal lIMITE, decimal cOMISSAO)
        {
            TAB_OBJLOJA tAB_OBJLOJA = new TAB_OBJLOJA();
            tAB_OBJLOJA.ARM = aRM;
            tAB_OBJLOJA.ANO = aNO;
            tAB_OBJLOJA.MES = mES;
            tAB_OBJLOJA.LIMITE = lIMITE;
            tAB_OBJLOJA.COMISSAO = cOMISSAO;
            return tAB_OBJLOJA;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for ARM in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string ARM
        {
            get
            {
                string value = _ARM;
                OnGetARM(ref value);
                return value;
            }
            set
            {
                if (_ARM != value)
                {
                  OnARMChanging(ref value);
                  ReportPropertyChanging("ARM");
                  _ARM = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("ARM");
                  OnARMChanged();
              }
            }
        }
        private string _ARM;
        partial void OnGetARM(ref string value);
        partial void OnARMChanging(ref string value);
        partial void OnARMChanged();
    
        /// <summary>
        /// There are no comments for ANO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public int ANO
        {
            get
            {
                int value = _ANO;
                OnGetANO(ref value);
                return value;
            }
            set
            {
                if (_ANO != value)
                {
                  OnANOChanging(ref value);
                  ReportPropertyChanging("ANO");
                  _ANO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("ANO");
                  OnANOChanged();
              }
            }
        }
        private int _ANO;
        partial void OnGetANO(ref int value);
        partial void OnANOChanging(ref int value);
        partial void OnANOChanged();
    
        /// <summary>
        /// There are no comments for MES in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public short MES
        {
            get
            {
                short value = _MES;
                OnGetMES(ref value);
                return value;
            }
            set
            {
                if (_MES != value)
                {
                  OnMESChanging(ref value);
                  ReportPropertyChanging("MES");
                  _MES = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("MES");
                  OnMESChanged();
              }
            }
        }
        private short _MES;
        partial void OnGetMES(ref short value);
        partial void OnMESChanging(ref short value);
        partial void OnMESChanged();
    
        /// <summary>
        /// There are no comments for LIMITE in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Required()]
        public decimal LIMITE
        {
            get
            {
                decimal value = _LIMITE;
                OnGetLIMITE(ref value);
                return value;
            }
            set
            {
                if (_LIMITE != value)
                {
                  OnLIMITEChanging(ref value);
                  ReportPropertyChanging("LIMITE");
                  _LIMITE = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("LIMITE");
                  OnLIMITEChanged();
              }
            }
        }
        private decimal _LIMITE = 0m;
        partial void OnGetLIMITE(ref decimal value);
        partial void OnLIMITEChanging(ref decimal value);
        partial void OnLIMITEChanged();
    
        /// <summary>
        /// There are no comments for COMISSAO in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        [System.ComponentModel.DataAnnotations.Required()]
        public decimal COMISSAO
        {
            get
            {
                decimal value = _COMISSAO;
                OnGetCOMISSAO(ref value);
                return value;
            }
            set
            {
                if (_COMISSAO != value)
                {
                  OnCOMISSAOChanging(ref value);
                  ReportPropertyChanging("COMISSAO");
                  _COMISSAO = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("COMISSAO");
                  OnCOMISSAOChanged();
              }
            }
        }
        private decimal _COMISSAO = 0m;
        partial void OnGetCOMISSAO(ref decimal value);
        partial void OnCOMISSAOChanging(ref decimal value);
        partial void OnCOMISSAOChanged();

        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            TAB_OBJLOJA obj = new TAB_OBJLOJA();
            obj.ARM = ARM;
            obj.ANO = ANO;
            obj.MES = MES;
            obj.LIMITE = LIMITE;
            obj.COMISSAO = COMISSAO;
            return obj;
        }

        #endregion
    
        #region Equals and GetHashCode methods

        public override bool Equals(object obj)
        {
          TAB_OBJLOJA toCompare = obj as TAB_OBJLOJA;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.ARM, toCompare.ARM))
            return false;
          if (!Object.Equals(this.ANO, toCompare.ANO))
            return false;
          if (!Object.Equals(this.MES, toCompare.MES))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + ARM.GetHashCode();
          hashCode = (hashCode * 7) + ANO.GetHashCode();
          hashCode = (hashCode * 7) + MES.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
